### PR TITLE
New, simpler SVG files.

### PR DESCRIPTION
**Pull request by johnwhitington**
This replaces pull request #669.

### CODE REVIEW

**Comment by pw374** [comment]
Thanks! :)

**Comment by pw374** [comment]
note: @johnwhitington if you put a `#` before the pull request number, it becomes a link to that PR (same for issues that are not PRs). ;)

**Comment by johnwhitington** [comment]
Unfortunately, when I type Alt-3 on a UK keyboard for a hash character in Github, it types the hash character, and then passes the keypress through to the browser, which opens Favourite website number 3. When I use the back button to go back, my comment is not saved, and I have to start over again.

If anyone knows a better way to type a hash quickly on a UK keyboard, let me know.

**Comment by johnwhitington** [comment]
Oh, on further experimentation it seems I'm hitting Cmd-3. So If I'm careful enough, it works. Thanks!

**Comment by Chris00** [comment]
You can also just copy the link.

**Pull request merged**
