### PR TITLE
Navbar low contrast ratio lighthouse issue resolved

### PR DESCRIPTION
**Pull request by jyotibalodhi**
# Issue Description

When we go to the `ocaml.org/learn/` and generating the lighthouse report, it gives an issue for the contrast ratio being too low between background and foreground colors as can be seen in the image below. I am solving the issue by off-screening the navbar menu when not in use and toggle it back when clicked.
In the image below the contact ratio issue can be seen on the right side as a lighthouse report.

Fixes # (issue)

#1489 

## Changes Made

I am solving the issue by off-screening the navbar menu when not in use and toggle it back when clicked.
In the image below the contrast ratio issue can be seen on the right side as a lighthouse report.

img1
 
I have tried to solve the issue by modifying the collapsed menu JS and making some changes in the `bootstrap.css`.

img 2

### CODE REVIEW

**Comment by gs0510** [comment]
@jyotibalodhi I can't really find a difference in the screenshot, can you also add a screencast so the change is more apparent? Thanks!

**Comment by jyotibalodhi** [comment]
> @jyotibalodhi I can't really find a difference in the screenshot, can you also add a screencast so the change is more apparent? Thanks!

Hello @gs0510 Actually the difference is not on the mobile screen view it's on the lighthouse report. In the first screenshot, on the right hand side you can see there's a error saying background and foreground colours low ratio. That is happening because of the navbar technically being there.  And in the second screenshot I have resolved rhe issue by toggling the nav menu items. 

This issue was raised by @patricoferris in a previous issue which I was solving that was closed but this point could not be worked upon. So I thought to work on this seperately.

**Comment by patricoferris** [comment]
Hi @jyotibalodhi, thanks! Seems like this does fix lighthouse issue from your images. I'm wondering what the accessibility implications of this are? The content is technically still on the screen somewhere right? So would screen-readers for mobile still see it (and read it)? These are open questions I don't actually know the answer to and was wondering if you do?

**Comment by jyotibalodhi** [comment]
Hi @patricoferris,  I just read about correctly hiding the off-screen content and made them inaccessible using tabs from here - https://web.dev/offscreen-content-hidden/. Adding the `display: none;` should make it unreadable for screen readers. Updating the Implementation in a while :).

**Comment by patricoferris** [comment]
Nice work @jyotibalodhi 👍 -- I think we could probably push this to staging to double-check soon.

**Comment by jyotibalodhi** [comment]
Yes, I think that would be great @patricoferris ! 
Also it would be great if you can assign me some medium issues, as I am much more familiar with the codebase now. :)

**Comment by avsm** [comment]
This fix looks good on staging (no visible changes, but Lighthouse improvement), so merging. Thanks @jyotibalodhi!

**Pull request merged**
