### PR TITLE
Improve companies page

### LINKED ISSUE #1287: Typos and grammatical errors on https://ocaml.org/learn/companies.html page
# Issue description

There are a couple of typos and grammatical errors in `Companies using OCaml` section of https://ocaml.org/learn/companies.html page. Below are the annotated screenshots of the specific sections.

**TrustInSoft, France**
image

**Digirati dba Hostnet, Brazil**
image

**CACAOWEB, United Kingdom and Hong Kong**
image
 
# How to reproduce the issue

Navigate to  `Companies using OCaml` section of https://ocaml.org/learn/companies.html page. Read about the following companies. You will notice a couple of typos and grammatical errors.
- TrustInSoft, France
- Digirati dba Hostnet, Brazil
- CACAOWEB, United Kingdom and Hong Kong

**Edit**
It would be a good idea to make general improvements to the page as well.

### PR DESCRIPTION
**Pull request by nibble0101**
# PR description

This PR improves the [companies page](https://ocaml.org/learn/companies.html) by fixing the following issues.

## Typos and grammatical errors
Before this fix there were a couple of typos on the [companies page](https://ocaml.org/learn/companies.html). You can view them before and after the fix in the following screenshots.
### TrustInSoft, France
**Before**
image
**After**
image

### Digirati dba Hostnet, Brazil
**Before**
image
**After**
image

### CACAOWEB, United Kingdom and Hong Kong
**Before**
image
 **After**
image

## Non sequential heading tags
Before this fix, there was a [`h4`](https://github.com/ocaml/ocaml.org/blob/master/site/learn/companies.md#disclaimer) element following `h2` skipping `h3` in between. It is important to have properly ordered headings that do not skip levels  because the headings convey the semantic structure of the page, making it easier to navigate and understand when using assistive technologies. The `h4` has been changed to `h3` to follow the correct semantic order.

## Styling to  improve appearance and  reading experience
It was difficult to to tell which block of text is describing which company as illustrated in the following before and after screenshots.
**Before**
image
**After**
image

# Related issue

If merged, this PR fixes #1287

### CODE REVIEW

**Comment by nibble0101** [comment]
@avsm  and @patricoferris. Let me know what you think of this fix.

**Comment by avsm** [comment]
This looks good to me! Pushed to staging.ocaml.org to verify before merging.

**Comment by nibble0101** [comment]
Thanks @avsm and @patricoferris . It looks good to me at the staging area.

**Comment by avsm** [comment]
Thanks for the PR and the checks. Merging!

**Pull request merged**
