### PR TITLE
FAQ and tutorials cleanup

### PR DESCRIPTION
**Pull request by dmbaturin**
These changes are quite opinionated. If you don't agree with some of them, I'll exclude them from the pull request.

The FAQ: soft questions like licensing and name capitalization placed after heavy technical questions look a bit odd, as of me. Also, rephrased the name meaning paragraph to make it clear that the original meaning is now irrelevant.

The compliation tutorial: since many people are going to use Oasis at some point, a pointer to it is useful I guess.

The tutorial list:
- Removed the Functional Unparsing paper reference. Excellent paper, but the code is in SML and the Printf module makes it of little practical interest for most people. :)
- Removed a dead link to a camlp4 tutorial (brion.inria.fr/gallium/index.php/Syntax_extension_tutorial)
- Removed the link to Understanding and Unraveling OCaml, since it's already in the books section.
- Removed the link to "A Concise Introduction to OCaml". It's indeed mostly valid, but it contains odd things like the SML syntax for loading files into the REPL, inaccurate references (Ullman's book is about SML, not CAML), and assertions that OCaml is purely functional, despite allowing side effects. People searching for tutorials will probably be confused, and since it's over 15 years old, it's unlikely we can convince the author to update it.
- Added references to PPX and GADT tutorials.

The book list:
- Removed the reference to the "Think OCaml" book. In its current state it will confuse beginners more than help them, since it's an incomplete translation of a Python book to OCaml: Python code snippets here and there, missing sections etc., and it probably leaves a wrong impression about the language as it pays very little attention to topics like data types and pattern matching and makes no mention of the module system at all, essentially teaching OCaml like it's Python. I hope the authors complete it some day.

### CODE REVIEW

**Comment by agarwal** [comment]
Thanks for this. It all looks okay to me, except for removing Think OCaml. I feel it's not our place to judge the books. If you can remove that from this pull request, I'll merge. And if you or others feel removing the book is correct, you can please open a new issue where discussion about that can continue.

**Comment by dmbaturin** [comment]
Good point. I've reverted that commit. Or should I make a new pull request that doesn't include traces of that commit at all?

**Comment by Chris00** [comment]
You can rebase your commits to remove it and force push to your branch — the PR will update itself!

**Comment by Chris00** [comment]
I also feel that the paper "Functional Unparsing" should be kept mentioned — maybe just as a remark or an alternative approach — because it is a useful technique to know for other situations.

**Comment by dmbaturin** [comment]
Thanks, Christophe! Looks like it worked.

As of functional unparsing, my point is not that it should not be referenced at all, just that it's probably not a good fit for the tutorials section.
Maybe it's a good idea to make a separate section for papers, they sure can be of great interest for people already familiar with OCaml, and some of them are not exactly easy to find unless someone told you its name, like the ZINC report, or the paper about relaxing value restriction. If you agree, I'll make a draft.

**Comment by Chris00** [comment]
> If you agree, I'll make a draft.

Thanks.  Please do!

**Comment by dmbaturin** [comment]
I didn't realize we already have a papers page (http://ocaml.org/docs/papers.html). Guess we can just expand it.

**Comment by dmbaturin** [comment]
Now when the controversial commit was removed and the book discussion was moved to an issue, this can be merged I guess?

**Comment by dmbaturin** [comment]
Ah, as of papers, I'll look into expanding the paper section, but it's going to be a separate pull request I guess.

**Comment by agarwal** [comment]
Thanks for reminding me to merge this. The _Functional Unparsing_ paper could indeed go to the _papers_ page. It'll be great if you can submit a pull request.

**Pull request merged**
