### PR TITLE
Fix syndications on news page

### LINKED ISSUE #1346: News Page: Create two or three columns on tabs for Syndications
Going through the news page on my tablet, the Syndications  section was right aligned and very lengthy.
There is a lot of space on the left area. So I suggest making it two or three columns on tablet rather that one column to make scrolling easier  for users.
### Issue
screencapture-ocaml-org-community-planet-2021-03-31-18_12_30

### Fix Proposed
ddd

If it's a good issue, then I would love to work on it.

### PR DESCRIPTION
**Pull request by dinakajoy**
# Issue Description
The Syndication section on News page gets right aligned on smaller devices and it is very lengthy making it more work to scroll through

Fixes #1346

## Changes Made
This PR floats it to the left and renders the feeds in three, two and single column(s) based on device width making it easy for users to navigate through .
The changes was tested on Chrome and Firefox browsers

tab

sm

xs

* **Please check if the PR fulfills these requirements**

- [x] PR is descriptively titled and links the original issue above
- [x] Before/after screenshots (if this is a layout change)
- [x] Details of which platforms the change was tested on (if this is a browser-specific change)
- [ ] Context for what motivated the change (if this is a change to some content)

### CODE REVIEW

**Comment by nibble0101** [comment]
@dinakajoy  Thanks for the PR. Good job.  I have a couple of observations.
1. In the first screenshot, there seems to be an overlap of the text, `"ocaml labs compiler hacking"`,  in the first column with the adjacent  one in the second column. How about having two columns instead of three for the first screenshot? 
2. I have noticed `rel = noopener` in the first commit. Are those changes related to this PR as well?

**Comment by dinakajoy** [comment]
I am working on number 1.
Regarding number 2, I worked on both the same day but this PR is strictly for news page not footer.

**Comment by dinakajoy** [comment]
@nibble0101 please can you help me resolve this conflicts? 
I have made the corrections - 2 columns not 3.
Thank you

correction

**Comment by nibble0101** [comment]
@dinakajoy  You have changed formatting of the file you worked on. That is why your PR is showing more than 300 lines of changes. You should note that this project doesn't have standard settings which auto formats code. If you commit formatting changes it will become difficult to review your code. I suggest you revert the formatting changes you committed so that you are left with only the changes related to the PR. Though I am not very certain,  I think only those with write access to this repository and you the person who opened the PR can  resolve merge conflicts.

**Comment by avsm** [comment]
Verified on staging.ocaml.org as a big improvement, so merging this. Thanks @dinakajoy!

@nibble0101 wrote:
> Though I am not very certain, I think only those with write access to this repository and you the person who opened the PR can resolve merge conflicts

That's right; you can see the permissions models for pushing to other people's PRs here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Pull request merged**
