### PR TITLE
Fixed alignment of links in community and images of hosting providers in Contributors

### LINKED ISSUE #1440: Repositioning images in Contributors
@patricoferris 
The images can be set a better positioning to make the page look symmetric. If this is something that you'd like to fix, I can work on it!
image

### LINKED ISSUE #1441: Realigning links in Contributors
@patricoferris 
I'd like to realign the two links to make them in line. It looks quite odd now.
image

Do let me know if I can fix this!

### PR DESCRIPTION
**Pull request by Srinithyee**
# Issue Description
Fixes issues #1440 and #1441.

## Changes Made
* The dimensions of color-transparent-icon.svg has been changed to fix #1441.
* The dimensions of the images of IBM, AWS, Rackspace and University of Cambridge in Contributors page has been changed to fix #1440.

# Issue #1440 
## Before:
image

## After:
image

# Issue #1441 
## Before:
image

##After:
image

* **Please check if the PR fulfills these requirements**

- [x] PR is descriptively titled and links the original issue above
- [x] Before/after screenshots (if this is a layout change)

### CODE REVIEW

**Comment by gs0510** [comment]
Hi @Srinithyee! Thanks for your PR. Can you open two separate ones, one for issue #1441 and another for #1440. It makes it easier for us to revert changes if something goes wrong. Thanks!

**Comment by Srinithyee** [comment]
@gs0510 Sure. I will do that in a bit. I thought this would be easier since it was only minor changes. But, okay, I will make two separate PRs.

**Comment by Srinithyee** [comment]
@gs0510 I've made two separate PRs ,i.e, #1484 and #1482 to fix issues #1441 and #1440 respectively.
I'll close this PR now :)

**Comment by dinakajoy** [comment]
Please @Srinithyee correct the PR mentions to 1482 and 1484. Thank you

**Comment by Srinithyee** [comment]
> Please @Srinithyee correct the PR mentions to 1482 and 1484. Thank you

@dinakajoy My bad! Sorry about that. Just corrected it :)

**Pull request closed without merging**
