### PR TITLE
remove a misleading discussion on single-line comments

### PR DESCRIPTION
**Pull request by iartarisi**
The discussion contains a personal (from whom?) suggestion about OCaml style and is inappropriate in a tutorial aimed at people who see the language for the first time.

### CODE REVIEW

**Comment by Chris00** [comment]
The tutorials were imported as they were and may need to be revised.  I agree that personal comments should be removed from the tutorials.  It would be nice however to add a page with some tricks for editors as indeed some may wonder how to alleviate the absence of single line comments (the comment was not mine in case you wonder).

**Comment by iartarisi** [comment]
Sure, but I think that building a page with editor tricks is a separate issue and cleaning up this section a bit is still a good step on its own. After all, this tutorial looks to be about learning the language, not its development environment.

**Comment by Chris00** [comment]
OK, I have opened a separate issue for that.

**Comment by iartarisi** [comment]
Cool, thanks!

**Pull request merged**
