### PR TITLE
Changes in layout of icons and meetings in OCaml Community Page

### PR DESCRIPTION
**Pull request by Kanak1081**
In Community page, under the 'Ocaml around the web' section, I have arranged all the 9 icons in three different rows. They look pretty symmetrical now. Also they are equal in size.

### CODE REVIEW

**Comment by avsm** [comment]
Thanks for the contribution, @Kanak1081! I've pushed this change to the staging site at https://staging.ocaml.org/ so we can look at it against the live site.

**Comment by Kanak1081** [comment]
Hey @avsm that's my pleasure to contribute :) . I can see that you have pushed the code in https://staging.ocaml.org/ and I saw that the code has some differences from the code that I have generated a Pull Request for. And so, the result is not as expected.
If, I am not wrong, the code that is pasted right now in https://staging.ocaml.org/ is a bit incorrect. Can you please check !

**Comment by Kanak1081** [comment]
Hi @avsm. How are you doing :) ? I have added two more commits to the community page and changed the layouts for OCaml Meetings, updated them with latest three and styled them a bit. I would be more than happy to know your suggestions. Thanks !

**Comment by avsm** [comment]
Hi @Kanak1081 -- would you be able to post before/after screenshots of the page as you see it?  I'm seeing this at https://staging.ocaml.org/community/ so there is some sort of rendering error:

image

**Comment by Kanak1081** [comment]
Yes @avsm ☺
Before : 
Screenshot (703)

After : 
Screenshot (701)

**Comment by avsm** [comment]
Thanks @Kanak1081 -- from your screenshots, it appears that your changes have also modified the layout of the "meetings" and "news" columns, as well as changing the icons in "OCaml Around the Web". Would you be able to localise the changes so that you only modify the icon layouts?  The "meetings" and "news" columns should be as they were before.

**Comment by patricoferris** [comment]
Looking great @Kanak1081 -- agree with everything Anil said. Stylistically the columns should be fine for meetings, from the original issue #1270 I think we just want to keep the improved grid layout for the icons and the updated meeting data, the actual style for these columns can remain as is (EDIT: I mean as they are currently on ocaml.org).

If that doesn't make sense please let me know. Thanks again :))

**Comment by avsm** [comment]
Just converting this into a draft PR until the requested changes have been made (no rush!)

**Comment by Kanak1081** [comment]
Hi, @avsm , as of now, I have closed the pull request as I can see that there are many Outreachy applicants who are willing to contribute for this issue. My PR was actually hindering their work a bit. Looking ahead for doing more contributions for OCaml .😊

**Pull request closed without merging**
