### PR TITLE
Improved footer content columns on tablet view

### PR DESCRIPTION
**Pull request by Goodiec**
# Issue Description
This a fix for #1338 

Please include a summary of the issue.
The content columns of the footer are not properly arranged on screen sizes between 767px and 481px
Fixes # (issue)

## Changes Made
Made changes to the ocamlorg.css file to improve the footer display on tablet view and also added padding-top to the footer.

Please describe the changes that you made.
Changed the footer CSS to display two columns per row on the mentioned screen sizes, increased the font size of the h1 elements of the footer, and also added padding to the top of the footer so it looks better and uniforms with the padding at the bottom of the footer.
Here's the before and after images:

before
after

* **Please check if the PR fulfills these requirements**

- [x] PR is descriptively titled and links the original issue above
- [x] Before/after screenshots (if this is a layout change)
- [x] Details of which platforms the change was tested on (if this is a browser-specific change)
- [x] Context for what motivated the change (if this is a change to some content)

### CODE REVIEW

**Comment by gs0510** [comment]
Thanks @Goodiec! LGTM! 🎉  The deployability has failed unrelated to your PR. If you force push again to the PR, the build will be retriggered and should pass :) Let me know if anything is unclear :)

**Comment by Goodiec** [comment]
> Thanks @Goodiec! LGTM! 🎉 The deployability has failed unrelated to your PR. If you force push again to the PR, the build will be retriggered and should pass :) Let me know if anything is unclear :)

Thank you @gs0510, thought the tests were failing because I was doing something wrong.

**Comment by avsm** [comment]
Many thanks, this looks right to me! Unfortunately, the changes to ocamlorg.css have conflicted with changes from #1355 and so do not apply cleanly to the current branch. Would you be able to assist with resolving the conflicts so that this can be merged?

**Comment by Goodiec** [comment]
> Many thanks, this looks right to me! Unfortunately, the changes to ocamlorg.css have conflicted with changes from #1355 and so do not apply cleanly to the current branch. Would you be able to assist with resolving the conflicts so that this can be merged?

Sure @avsm I'll do that in a short while. Thank you

**Comment by Goodiec** [comment]
> Many thanks, this looks right to me! Unfortunately, the changes to ocamlorg.css have conflicted with changes from #1355 and so do not apply cleanly to the current branch. Would you be able to assist with resolving the conflicts so that this can be merged?

I've fixed the conflict @avsm, kindly check. Thank you.

**Comment by avsm** [comment]
Confirmed in staging, and pushing to live. Thanks! One minor note: your editor is still making whitespace changes to the file that are unrelated to the change at hand -- I'll merge this one as I manually verified it, but it's generally good practise to avoid unrelated whitespace changes as they will conflict with other PRs.

**Comment by Goodiec** [comment]
> Confirmed in staging, and pushing to live. Thanks! One minor note: your editor is still making whitespace changes to the file that are unrelated to the change at hand -- I'll merge this one as I manually verified it, but it's generally good practise to avoid unrelated whitespace changes as they will conflict with other PRs.

Noted @avsm, thank you!

**Pull request merged**
