### PR TITLE
UI fixes: Moved the language selector `[ en fr ]` to the top-right corner of the page.

### PR DESCRIPTION
**Pull request by 0xull**
Patch: Changed the language selector [ en fr ] component to the top-right corner of the page: on the desktop, it's next to the edit button; on the phone that's next to the hamburger menu. This follows the left-to-right design layout that suggests the language selector should be in the top-right corner of the page, that's where people intuitively would look for it

Test: The responsiveness and consistency of the component across all screen resolution, and also ascertain how intuitive the change truly is to design layout.

Previous: 
ocaml-prev

Recent: 
ocaml-recent

### CODE REVIEW

**Comment by patricoferris** [comment]
Hmm, this looks like it has recommited lots of other people's work no? Perhaps something went wrong during a rebase/merge on the `master` branch? The changes look good, but it would be good to disentangle them from other commits and code changes before merging into `master`?

**Comment by avsm** [comment]
Hm, pushing to staging also closed to this PR. That's unexpected.

**Comment by avsm** [comment]
@IkehAkinyemi the PR looked good to me, but as @patricoferris says something went wrong with git along the way. Would you be able to generate a fresh PR with your changes against the `master` branch of this repository?

**Comment by 0xull** [comment]
Okay, I will work on that right away.

**Pull request merged**
