### PR TITLE
Move book covers over from caml.inria.fr

### PR DESCRIPTION
**Pull request by johnwhitington**

### CODE REVIEW

**Comment by agarwal** [comment]
Can you please import the images to the [ocaml.org-media](https://github.com/ocaml/ocaml.org-media) repo, which we use for static content to avoid bloating this repo. So you need 2 pull requests: one here for the URL changes, and one in ocaml.org-media for the images. The ocaml.org-media repo is simple. All files are copied directly to the server, so simply put the files in a directory structure corresponding to the desired URL.

**Comment by Chris00** [comment]
@johnwhitington May you explain why you closed that issue?  I do not see any PR on  ocaml.org-media — not that _you_ have to do it but I believe that this issue should stay open till then.

**Comment by johnwhitington** [comment]
Oh, I had planned to do it now. I'll reopen, and close when it's done.

**Comment by Chris00** [comment]
On Thu, 4 Jun 2015 09:47:36 -0700, John Whitington wrote:

> Oh, I had planned to do it now. I'll reopen, and close when it's done.

OK.  Thanks.

**Comment by johnwhitington** [comment]
See pull request 666.

**Comment by agarwal** [comment]
For the record, this pull request superseded by #666 and ocaml/ocaml.org-media#7.

**Pull request closed without merging**
