### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by Lontchi12**
# Issue Description
https://github.com/ocaml/ocaml.org/issues/1413
Please include a summary of the issue.
The success.fr.html page had issues on the translation and wasn't well aligned and some content on the english page were not available in the french page so i adjusted and fixed that
Fixes # (issue)
Translated the page, adjusted alignments and put more content

## Changes Made
Quelques succès – OCaml - Google Chrome 4_13_2021 10_00_37 PM
Quelques succès – OCaml - Google Chrome 4_13_2021 10_01_01 PM
Quelques succès – OCaml - Google Chrome 4_13_2021 10_01_12 PM
Quelques succès – OCaml - Google Chrome 4_13_2021 10_01_51 PM
Quelques succès – OCaml - Google Chrome 4_13_2021 10_01_42 PM
Please describe the changes that you made.

* **Please check if the PR fulfills these requirements**
Translated the page, adjusted alignments and put more content in the ocaml.org/learn/success.fr.html page
- [ ] PR is descriptively titled and links the original issue above
- [ ] Before/after screenshots (if this is a layout change)
- [ ] Details of which platforms the change was tested on (if this is a browser-specific change)
- [ ] Context for what motivated the change (if this is a change to some content)

### CODE REVIEW

**Comment by Lontchi12** [comment]
Hello Please check this PR and merge if there are no issues. Thank you

**Comment by patricoferris** [comment]
Hmmm something is very weird about this PR. I don't see any of the changes you mentioned @Lontchi12? In fact this PR is trying to merge our `staging` branch into `master`, I can't imagine any scenario where we'd want to do that as the `staging` branch is used for testing (see https://staging.ocaml.org). For this reason I'm going to close the PR. Feel free to open a new PR with the changes you wanted to add, relating to #1413.

**Comment by Lontchi12** [comment]
Good day @patricoferris thanks for the remark, i actually had an issue commiting my changes and pushing, when i do the changes and see them on my local machine and come to do git status, they tell me my working branch is clean and there is nothing to commit meanwhile i have actually done changes as you can see on the screenshots i sent, so i just pushed like that i guess that is why the changes didn't come up as well, Please if you have any idea of how i can commit these changes and push them i'll really appreciate.  so i came and just did a PR without knowing i am really sorry about that. i am kindly waiting for help from you Thank you

**Comment by patricoferris** [comment]
Hi @Lontchi12,

Please make sure you are editing the markdown documents and not the HTML ones inside the `ocaml.org/...` directory. This is the only thing I can think of that might be causing your issue.

**Comment by Lontchi12** [comment]
Hello @patricoferris

 Thank you for the remark, i have done that already and i have opened another PR for please kindly check and review Thank You

**Pull request closed without merging**
