### PR TITLE
Fixed Spacing of books in Learn/books.html

### PR DESCRIPTION
**Pull request by Bhavika-Gianey**
# Fixed Spacing of books in Learn/books.html (https://www.ocaml.org/learn/books.html)

Fixes # (1373)

## Before

old3

## After

new

* **Please check if the PR fulfills these requirements**

- [x] PR is descriptively titled and links the original issue above
- [x] Before/after screenshots (if this is a layout change)
- [x] Details of which platforms the change was tested on (if this is a browser-specific change)
- [x] Context for what motivated the change (if this is a change to some content)

### CODE REVIEW

**Comment by avsm** [comment]
This doesn't seem right at first glance -- none of the other sections require the three forced `<br />` insertions. Can you spot why the Italian section layout isn't working, but the other ones are?

**Comment by Bhavika-Gianey** [comment]
> This doesn't seem right at first glance -- none of the other sections require the three forced `<br />` insertions. Can you spot why the Italian section layout isn't working, but the other ones are?
Yes, you are right @avsm. I found my mistake. Actually, there was no description added to that book, and also it was right floated. I just need to remove that predefined CSS of the right float. Will submit a new Pr with the new changes.

**Comment by Bhavika-Gianey** [comment]
> This doesn't seem right at first glance -- none of the other sections require the three forced `<br />` insertions. Can you spot why the Italian section layout isn't working, but the other ones are?



> This doesn't seem right at first glance -- none of the other sections require the three forced `<br />` insertions. Can you spot why the Italian section layout isn't working, but the other ones are?

Yes, you are right @avsm. I found my mistake. Actually, there was no description added to that book, and also it was right floated. I just need to remove that predefined CSS of the right float. Will submit a new Pr with the new changes.

**Comment by Bhavika-Gianey** [comment]
@avsm, I have created a new pull request.  kindly review it .
#1465

**Comment by avsm** [comment]
Thanks! I'll close this one in favour of that.

**Pull request closed without merging**
