### PR TITLE
External nature of packages in the navigation bar has been made visible by adding an external link icon.

### LINKED ISSUE #1308: Make external nature of `Packages` navigation item visible
This would be a **good first issue** for anyone looking to get started improving and contributing to OCaml.org.

The header contains six navigation items: `OCaml`, `Lean`, `Documentation`, `Packages`, `Community` and `News`. All of them apart from `Packages` navigate inside ocaml.org, whereas `Packages` links to an external page (opam.ocaml.org). I suggest to make that visible by marking `Packages` with an external link icon.

### PR DESCRIPTION
**Pull request by Muskan-sam**
# Issue Description

The packages navigation item on the navigation bar redirects the user to opam.ocaml.org which is an external site. It seemed a bit confusing to some of the user's as they couldn't get back to the home page ocaml.org from the opam.ocaml.org site. To deal with this , the packages navigation item on the navigation was to be marked with an external link icon. This would indicate the user about the external nature of the packages navigation item on the navigation bar.

Fixes #1308 

## Changes Made

I have added the external link icon to the packages navigation item on the navigation bar of ocaml.org

**before:**
image

**after:** 
image

 

* **Please check if the PR fulfills these requirements**

- [ ] PR is descriptively titled and links the original issue above
- [ ] Before/after screenshots (if this is a layout change)
- [ ] Details of which platforms the change was tested on (if this is a browser-specific change)
- [ ] Context for what motivated the change (if this is a change to some content)

### CODE REVIEW

**Comment by gs0510** [comment]
@Muskan-sam, thanks for you PR. The PR changes more than 5000 files which is most definitely incorrect. When you do a git add, please only add the files that you changed and then commit them. Can you try to do that and let me know if you face any issues, thanks!

**Comment by Muskan-sam** [comment]
> @Muskan-sam, thanks for you PR. The PR changes more than 5000 files which is most definitely incorrect. When you do a git add, please only add the files that you changed and then commit them. Can you try to do that and let me know if you face any issues, thanks!

@gs0510 After making changes to the file when I ran `make` command on my terminal it , after completing the process the terminal's prompt was gone. I created a backup of `~/.bashrc` and replaced it with a new one. Maybe that's the reason it's showing more than 5000 files were changed. What should I do now?

**Comment by gs0510** [comment]
You can undo your commit with `git reset HEAD~` and then git add and git commit the file you actually made changes to and then do a git force push.

**Comment by Muskan-sam** [comment]
> You can undo your commit with `git reset HEAD~` and then git add and git commit the file you actually made changes to and then do a git force push.

@gs0510  I tried `git reset HEAD~` but that didn't work. So I had to setup the project again on my system and make all the changes. But after making the changes when I try `git status` it shows me the following results ,
image
image
image

what should I do next?

**Comment by gs0510** [comment]
There's a problem with line endings because Windows does it differently. You need to setup git so that you can have Unix-like line endings instead of Windows style line endings @Muskan-sam

**Comment by avsm** [comment]
The change looks good to me, but this individual PR definitely needs to be reopened without the line endings changes (as that changes the entire site). I'll close this PR, but please do re-open another one once you have changed your developer client to not rewrite line endings as @gs0510 suggested. Thanks!

**Comment by Muskan-sam** [comment]
> The change looks good to me, but this individual PR definitely needs to be reopened without the line endings changes (as that changes the entire site). I'll close this PR, but please do re-open another one once you have changed your developer client to not rewrite line endings as @gs0510 suggested. Thanks!

@avsm okay I will do that :)

**Pull request closed without merging**
