### PR TITLE
Fixed an omitted '#' for a directive call. Updated weberizer executable name.

### PR DESCRIPTION
**Pull request by xandkar**

### CODE REVIEW

**Comment by Chris00** [comment]
The version of weberizer in OPAM seems to use the old name.  I'll make a new release soon.

**Comment by Chris00** [comment]
Please submit a pull request for the missing “#” only.

**Comment by xandkar** [comment]
Not sure that I understand - which is the outdated name, 'weberizer_compile' or 'weberizer'? Both, the latest OPAM build and a fresh clone & build of weberizer repo, seem to be using 'weberizer_compile' name.

**Comment by agarwal** [comment]
The new name is 'weberizer'. This is what it's called in the latest head of
the weberizer repo (you must not be getting the latest head). But this
version is not yet released formally in opam.

**Comment by xandkar** [comment]
Got it. Just submitted another pull request for "#" only.

However, weberizer issue is still a mystery - I see your commit that changed the name, but the build process still produces an executable named "weberizer_compile.native". What else can I be missing?

**Comment by agarwal** [comment]
That's the executable in your working directory, but oasis renames it at
install time. So do `make install`. Where it gets installed depends on what
--prefix option you used when doing `ocaml setup.ml -configure`. I
recommend setting --prefix to the root of your ocaml installation. Then all
your ocaml related stuff gets installed under one directory.

Or better yet, if you're using opam (which you should be), just do this:

opam pin weberizer /path/to/local/weberizer
opam install weberizer

and opam will do its magic! When Christophe updates the opam-repository,
you'll do

opam pin weberizer none
opam update
opam upgrade

and you'll no longer be using your local copy.

**Comment by Chris00** [comment]
Weberizer 0.7.2 is now in opam-repository.

**Comment by xandkar** [comment]
Cool. Just updated.

Thank you for the detailed help, Ashish!

Still, all of that just to get a predictable filename? My spidey senses are tingling... :)

**Pull request closed without merging**
