### PR TITLE
Added EPITA to schools that teach OCaml

### PR DESCRIPTION
**Pull request by atestu**
It's the first language we learn there, extensively for the first two years.

### CODE REVIEW

**Comment by jcapron** [comment]
:+1:

**Comment by amirmc** [comment]
Thanks for the PR! I also managed to find the [page](http://www.epita.fr/international/international-bachelor-academic-program.aspx) on the site too.

Did you add EPITA to the [Google map](https://www.google.com/maps/d/edit?mid=zk8_K4G_usic.kkzYvEvqV44Q)?  — instructions are on the page as: _"Click on the relevant layer (e.g., US,EU), search for your University, click on the marker and click on "Add to map", fill in the info fields and you are done!"_

**Comment by AlexandreAbraham** [comment]
Part of the material is here: http://algo-td.infoprepa.epita.fr/
Thanks for thinking about that @atestu ;)

**Comment by atestu** [comment]
@amirmc done!

**Comment by amirmc** [comment]
Thanks @atestu! Are you guys really using OCaml 3.11? I'd have thought everyone would be on 4.01.0 at least.

**Comment by atestu** [comment]
I honestly don't know, last time I coded in OCaml there was in 2008. Are there big differences between 3 & 4? Like Python 2/3?

**Comment by amirmc** [comment]
The [changelog](http://caml.inria.fr/pub/distrib/ocaml-4.02/notes/Changes) is pretty big between 3.11.2 and 4.01 (with some potentially breaking changes). I don't think there's anything as big as the Python 2/3 incompatibilities, which is why it seems odd to me that the course instruction page mentions such an old version.

**Pull request merged**
