### PR TITLE
New community-large.svg which should render ok on Safari

### PR DESCRIPTION
**Pull request by johnwhitington**
I converted to PDF using an online tool, then decompressed it using cpdf, modified the PDF manually in a text editor, and fixed it with cpdf. Then, I used another online tool to convert back to SVG.

It now consists solely of plain shapes. If this one works ok, I'll do the other failing one, and perhaps clean up all of them.

### CODE REVIEW

**Comment by pw374** [comment]
It does work for me, based on comparing https://github.com/johnwhitington/ocaml.org/blob/master/site/img/community-large.svg to https://github.com/ocaml/ocaml.org/blob/master/site/img/community-large.svg.

**Comment by johnwhitington** [comment]
Excellent. This can be merged then, unless anyone objects.

**Comment by agarwal** [comment]
I get a merge conflict. I think I can do it manually, but @johnwhitington maybe you want to rebase and push again?

**Comment by johnwhitington** [comment]
Yet another of a hundred things about git I don't understand well enough to do :-)

Have manually prepared another pull request #670, and will close this one.

**Pull request closed without merging**
