### PR TITLE
[WIP] Fix Japanese translation

### PR DESCRIPTION
**Pull request by zakki**
Where should I talk about translation improvement?

### CODE REVIEW

**Comment by Chris00** [comment]
@zakki Thanks for your work.  You can discuss it here but you may also want to send an email to the main OCaml mailing list in order to gather Japanese speaking collaborators (I personally do not understand Japanese).

**Comment by Chris00** [comment]
@camlspotter This is not clear to me: how should line 30 be fixed?  @zakki May you fix it as @camlspotter mentions (push an additional commit to your branch).  One this is done, I can merge it.

**Comment by camlspotter** [comment]
Oh I meant all look ok to me.

**Comment by Chris00** [comment]
Merged — via [cherry-pick](https://github.com/ocaml/ocaml.org/commit/4d7ec1db689d536eb2a78a96d343e2a629d9dd88).

**Pull request closed without merging**
