### PR TITLE
opam.ocaml.org: Add a link to check.ocamllabs.io

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Idea from @dbuenzli

### CODE REVIEW

**Comment by avsm** [comment]
thanks!

**Comment by dbuenzli** [comment]
It seems the change never made it to http://opam.ocaml.org/

**Comment by dbuenzli** [comment]
Ping @kit-ty-kate

**Comment by kit-ty-kate** [comment]
I don't have access to this. @avsm?

**Comment by dbuenzli** [comment]
Still an issue.

**Comment by kit-ty-kate** [comment]
@dbuenzli I asked around.. Turns out the opam.ocaml.org website isn't pulled from this repository but from opam2web. I opened the corresponding PR there https://github.com/ocaml-opam/opam2web/pull/196. Hopfully this time it works 😞

**Comment by kit-ty-kate** [comment]
:tada:
scrn-2021-08-23-13-48-11

**Pull request merged**
