### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by msprotz**
The descriptions for the various windows flavors was a little bit misleading and out-of-date. I've hopefully fixed that.

### CODE REVIEW

**Comment by pw374** [comment]
This patch looks good to me. I don't know why this hasn't been merged yet... but now it has conflicts... :-/

**Comment by pw374** [comment]
Thanks @msprotz

**Comment by lefessan** [comment]
Since your patch is touching the part on OCPWin, could you add back the link, since the problem for which it has been removed has now been known to be fixed for the last four months ?

**Comment by pw374** [comment]
Apologies, I thought I was careful enough for that link to stay! But I guess in all the rebase/not-rebase attempts for merging this, I missed something. Thanks for pointing this mistake.

Since we're at it, I wondered if we should put OCPWin before the other ways, because OCPWin seems to be the easiest way.

**Comment by pw374** [comment]
Oh! But I was careful enough not to let that link disappear! Don't rely on the diff of this PR, because the merge was not done on Github, so the diff does not show at all the result of the merge!

**Pull request merged**
