### PR TITLE
add dev.to to community links

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I didn't update French page. Should just decide to either hire translators or remove partially translated

**Comment by avsm** [comment]
Thanks for the contribution. Given it's just a single line, would you mind synching this with the translations as well while we're here?

**Comment by ghost** [comment]
Updated

**Comment by avsm** [comment]
Thanks!

**Comment by ghost** [comment]
The image is enormous, I will try to resize later

**Pull request merged**
