### PR TITLE
OCaml 2017: include references to extended abstract and slides + local archives

### PR DESCRIPTION
**Pull request by gasche**
The imported PDFs are fairly small, 6.2Mio in total.

### CODE REVIEW

**Comment by Chris00** [comment]
Previous year documents were uploaded to https://github.com/ocaml/ocaml.org-media  Could you please make a PR against that repo (and update this one for the links only)?

**Comment by gasche** [comment]
Oh, sorry, I forgot about that repo. I'll do this, thanks!

**Comment by gasche** [comment]
So I created an ocaml.org-media PR at https://github.com/ocaml/ocaml.org-media/pull/10. Do I currently understand that the hierarchies of the two sites are silently merged at build time, so that I can refer to a file in `ocaml.org-media/meetings/ocaml/2017` as if it was directly in `ocaml.org/site/meetings/ocaml/2017`?

**Comment by Chris00** [comment]
I think so.  No time to confirm — so I merge and we'll see! ;-)

**Pull request merged**
