### PR TITLE
Add Dernier Cri in companies using OCaml.

### PR DESCRIPTION
**Pull request by dannywillems**
@Chris00 asked to add Dernier Cri when I told him about it.

@xvw Could you confirm and check? I think a more complete description will be better. I don't know if it's `Dernier Cri` or `Derniercri`. Is the logo good?

### CODE REVIEW

**Comment by xvw** [comment]
Yes, it is `Dernier Cri`. We are based in Lille and Paris. 
Thanks a lot ! 

(Yes, it is the perfect logo ;) )

**Comment by dannywillems** [comment]
@xvw I fixed the location. Do you want to add something else in the description. I think it's not enough.

**Comment by Chris00** [comment]
Can you put it in alphabetical order?

**Comment by xvw** [comment]
@dannywillems it is perfect for the location ! Thanks a lot ! 
In fact we use principally OCaml for internal tools and React Native for mobile app and Elixir/Phoenix + React/Elm for classic web app. 
(I'm trying to push Ocsigen in our stack).

**Comment by dannywillems** [comment]
@Chris00 Done.

@xvw Ok. I modified.

**Pull request merged**
