### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by redianthus**
Hi,

I fixed warnings I got when doing `make`.

### CODE REVIEW

**Comment by redianthus** [comment]
Is there a special reason why we are testing against `4.02.3` ?

The build is failing with `Error: Unbound value String.lowercase_ascii` which is not surprising. :)

If we don't need to keep compatibility with `4.02.3` then we can just drop this in the CI file and merge the PR. (I can open a PR to drop `4.02.3` if needed)

**Comment by agarwal** [comment]
I'm not sure what version of OCaml is being run on the build server. @avsm @Chris00 I lost track long ago about how the site is actually built and deployed. Can you confirm if testing against 4.02.3 is needed. Thanks.

**Comment by pmetzger** [comment]
I think it would be best if the build server for the site was running 4.06.1 at this point. It would mean we could stick to modern constructs for everything.

**Comment by Chris00** [comment]
4.02.3 is run on the server — at the time because of problems with dependencies.  I'll try to update it tomorrow.

**Comment by redianthus** [comment]
@Chris00, is there some dependency trouble to fix ? Or is it just a matter of updating OCaml on the server ? Just to know if there's something more I can do. :)

**Comment by Chris00** [comment]
It is updated on the server but there is still a problem with Travis.

**Comment by redianthus** [comment]
Yes, I just have to remove it from Travis. Will do.

EDIT: it appears you already did it :) we just have to wait for the build to pass

**Comment by redianthus** [comment]
@Chris00, I'm not sure what's going on with the `4.05.0` build.

On the [last master build](https://travis-ci.org/ocaml/ocaml.org/jobs/388257176#L949), this seems to be handled correctly. [Here](https://travis-ci.org/ocaml/ocaml.org/jobs/388318777#L933), the build is stopped because there's not output produced. I'm not sure if it's because no answer is provided to opam (why ?) or if it's just because the next step is too long...

**Comment by Chris00** [comment]
There is a problem with the script to retrieve the latest opam package.  Unfortunately, that thing breaks regularly...  I'll try to write something taking another approach — but it is unlikely to happen before July.

**Comment by redianthus** [comment]
I'll try to see if I can fix it. Do you want to wait until it's fixed to merge this ?

**Pull request merged**
