### PR TITLE
Layout Improvement

### PR DESCRIPTION
**Pull request by jyotibalodhi**
Hello @patricoferris as I showed previously I have fixed the extra spacing on the right side of the website, and also done a few style fixes of the code.  Kindly review the PR. Thanks!

### CODE REVIEW

**Comment by avsm** [comment]
@jyotibalodhi, many thanks for contributing this PR. It's a little difficult to review since you have committed a lot of whitespace changes to the CSS at the same time as making your change, and so the diff (in the "files") tab is quite large.

Would it be possible for you to remove the whitespace changes to the CSS, and just commit the modified CSS line instead? Also, a couple of of before/after screenshots about which pages are affected would be useful in order to compare the results.  Thanks!

**Comment by jyotibalodhi** [comment]
Hello @avsm I will do the required changes. Also I have shown the ss of the changes previously in my comment but will share the needful Screenshots also. Thanks!

**Comment by patricoferris** [comment]
Hi @jyotibalodhi, it looks like the white space changes are still there (i.e. the reformatting of the CSS). This repository doesn't have any tooling for reformatting but modern editors sometimes do it for you on save, maybe that's what's causing this? Whilst I agree it looks and reads better, it also isn't the place for it in this PR (it makes it harder to review). If you could 'unformat' the CSS and just commit the changes related to the issue and PR that would be fantastic. Maybe we can look into standard formatting tools later?

**Comment by jyotibalodhi** [comment]
> Hi @jyotibalodhi, it looks like the white space changes are still there (i.e. the reformatting of the CSS). This repository doesn't have any tooling for reformatting but modern editors sometimes do it for you on save, maybe that's what's causing this? Whilst I agree it looks and reads better, it also isn't the place for it in this PR (it makes it harder to review). If you could 'unformat' the CSS and just commit the changes related to the issue and PR that would be fantastic. Maybe we can look into standard formatting tools later?

Hello @patricoferris yes the editor did the style changes on save. I am working on that, will make the PR today with only the necessary changes.

**Comment by jyotibalodhi** [comment]
Hello @avsm @patricoferris  I have raised the PR with the required changes. Kindly have a look! #1300

**Comment by avsm** [comment]
Thanks; closing this PR in favour of https://github.com/ocaml/ocaml.org/pull/1300 which has just the desired change.

**Pull request closed without merging**
