### PR TITLE
Use the same OPAM new package table generation system as opam2web

### LINKED ISSUE #253: Add code to generate a package table
Moved from from https://github.com/ocamllabs/sandbox-ocaml.org/issues/31
@pw374 is looking at this.

---

This is used on the front page and the platform page. Currently has placeholder text.

I'm hoping we can take existing code from opam2web which generated the tables at https://opam.ocaml.org

### LINKED ISSUE #326: list of recent package updates
Just to let you know that it's normal that the list is currently irrelevant, because there's been a huge git-renaming in opam-repository.

So it's going to be either alphabetically ordered or anti-alphabetically ordered, until there's been enough actual updates.

### LINKED ISSUE #412: New Packages Box Links to Wrong Versions and Has Wrong Dates
Table is currently:

```
    New packages

Package     Version     Date
weberizer   0.7.7   26 Feb 2014
bibtex2html 1.97    26 Feb 2014
glical  0.0.1   26 Feb 2014
oasis2opam  0.3.0   25 Feb 2014
mirage-xen  1.1.1   24 Feb 2014
oasis   0.3.0   23 Feb 2014
```

but the oasis2opam that was released on 25 Feb was 0.4.0 not 0.3.0 and bibtex2html was released on 31 Jan and only updated to add the correct hevea dep on 26 Feb.
#326 and #253 are related.

opam2web 1.3.0 and opamfu 0.1.0 contain a high level new package table generator and a low-level package universe creation date extractor respectively.

### PR DESCRIPTION
**Pull request by dsheets**
Fixes #253. Fixes #326. Fixes #412.

Not the prettiest implementation or least redundant but it gets the job done. The server will need to have opam installed and periodically run

``` bash
opam update
script/generate_opam_update_list
make
```

or something similar. I don't really know what the present update script looks like because it's not in this repository for some reason.

Also, I didn't know whether to list more transitive dependencies in the README or if just opam2web >= 1.3.1 was enough.

It's probably wise to play around with this a little locally and then on a test server before actually deploying but I have no idea what the deploy procedures look like. I hope this works for you. I'll be happy to support this feature now and in the future.

### CODE REVIEW

**Comment by dsheets** [comment]
Also fixes #439.

**Comment by dsheets** [comment]
It should be noted that the default opam remote will need to be changed to a git repository and all instances of `opam update` will need to be changed to `cd opam-repository && git pull && opam update`.

**Comment by dsheets** [comment]
Is there anything I can do to help integrate this PR?

**Comment by pw374** [comment]
On 15 Mar 2014, at 15:48 pm, David Sheets notifications@github.com wrote:

> Is there anything I can do to help integrate this PR?

I’ll try to integrate this PR today. I’ll ask for your help if anything goes wrong :-)

**Comment by pw374** [comment]
When I try to opam-install the packages required for building ocaml.org, I get this message:
`# ocamlfind: _build/src/client/opam-client.cmxa: No such file or directory`
for opam-lib.1.1.1 on debian wheezy / opam 1.1.1

---

```
$ opam install opam-lib
The following actions will be performed:
 - install opam-lib.1.1.1
1 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove

=-=-= Installing opam-lib.1.1.1 =-=-=
opam-lib.1.1.1 Downloading https://github.com/OCamlPro/opam/archive/1.1.1.tar.gz
Building opam-lib.1.1.1:
  ./configure --prefix=/home/phil/.opam/4.00.1 --mandir=/home/phil/.opam/4.00.1/man
  make META
  make with-ocamlbuild
  make libinstall-with-ocamlbuild
  rm opam.install
[ERROR] The compilation of opam-lib.1.1.1 failed.
Removing opam-lib.1.1.1.
  ocamlfind remove opam


===== ERROR while installing opam-lib.1.1.1 =====
# opam-version 1.1.1
# os           linux
# command      make libinstall-with-ocamlbuild
# path         /home/phil/.opam/4.00.1/build/opam-lib.1.1.1
# compiler     4.00.1
# exit-code    2
# env-file     /home/phil/.opam/4.00.1/build/opam-lib.1.1.1/opam-lib-19631-e7966f.env
# stdout-file  /home/phil/.opam/4.00.1/build/opam-lib.1.1.1/opam-lib-19631-e7966f.out
# stderr-file  /home/phil/.opam/4.00.1/build/opam-lib.1.1.1/opam-lib-19631-e7966f.err
### stdout ###
# ...[truncated]
# /home/phil/.opam/4.00.1/bin/ocamlfind ocamlopt -c -package dose3 -package cudf -package cmdliner -package ocamlgraph -package re.perl -package re.str -package re.pcre -package re.glob -I src/scripts -I src/client -I src/solver -I src/core -I src/repositories -o src/scripts/opam_mk_repo.cmx src/scripts/opam_mk_repo.ml
# /home/phil/.opam/4.00.1/bin/ocamlfind ocamlopt -c -package dose3 -package cudf -package cmdliner -package ocamlgraph -package re.perl -package re.str -package re.pcre -package re.glob -I src/scripts -I src/client -I src/solver -I src/core -I src/repositories -o src/scripts/opam_repo_check.cmx src/scripts/opam_repo_check.ml
# /home/phil/.opam/4.00.1/bin/ocamlfind ocamlopt -c -package dose3 -package cudf -package cmdliner -package ocamlgraph -package re.perl -package re.str -package re.pcre -package re.glob -I src/scripts -I src/client -I src/solver -I src/core -I src/repositories -o src/scripts/opam_stats.cmx src/scripts/opam_stats.ml
# /home/phil/.opam/4.00.1/bin/ocamlfind ocamlopt -c -package dose3 -package cudf -package cmdliner -package ocamlgraph -package re.perl -package re.str -package re.pcre -package re.glob -I src/scripts -I src/client -I src/solver -I src/core -I src/repositories -o src/scripts/opam_admin.cmx src/scripts/opam_admin.ml
# /home/phil/.opam/4.00.1/bin/ocamlfind ocamlopt -linkpkg -package dose3 -package cudf -package cmdliner -package ocamlgraph -package re.perl -package re.str -package re.pcre -package re.glob src/core/opamGitVersion.cmx src/core/opamJson.cmx src/core/opamMisc.cmx src/core/opamGlobals.cmx src/core/opamVersion.cmx src/core/opamProcess.cmx src/core/opamSystem.cmx src/core/opamFilename.cmx src/core/opamParallel.cmx src/core/opamPackage.cmx src/core/opamFormula.cmx src/core/opamCompiler.cmx src/core/opamRepositoryName.cmx src/core/opamSwitch.cmx src/core/opamVariable.cmx src/core/opamTypes.cmx src/core/opamFormat.cmx src/core/opamParser.cmx src/core/opamLexer.cmx src/core/opamLineLexer.cmx src/core/opamPath.cmx src/core/opamFile.cmx src/core/opamFilter.cmx src/core/opamRepository.cmx src/core/opamScript.cmx src/repositories/opamVCS.cmx src/repositories/opamDarcs.cmx src/repositories/opamGit.cmx src/repositories/opamHTTP.cmx src/repositories/opamHg.cmx src/repositories/opamLocal.cmx src/client/opamState.cmx src/client/opamAction.cmx src/solver/opamCudf.cmx src/solver/opamHeuristic.cmx src/solver/opamSolver.cmx src/client/opamConfigCommand.cmx src/client/opamPinCommand.cmx src/client/opamRepositoryCommand.cmx src/client/opamSolution.cmx src/client/opamSwitchCommand.cmx src/client/opamClient.cmx src/client/opamArg.cmx src/scripts/opam_depexts_change.cmx src/scripts/opam_mk_repo.cmx src/scripts/opam_repo_check.cmx src/scripts/opam_stats.cmx src/scripts/opam_admin.cmx -o src/scripts/opam_admin.native
# make libuninstall
# make[1]: Entering directory `/home/phil/.opam/4.00.1/build/opam-lib.1.1.1'
# ocamlfind remove opam
# make[1]: Leaving directory `/home/phil/.opam/4.00.1/build/opam-lib.1.1.1'
# ocamlfind install opam META _build/src/core/opam-core.a _build/src/core/opam-core.cma _build/src/core/opam-core.cmxa _build/src/core/opamPackage.cmi _build/src/core/opamRepositoryName.cmi _build/src/core/opamPath.cmi _build/src/core/opamFile.cmi _build/src/core/opamJson.cmi _build/src/core/opamFilename.cmi _build/src/core/opamSystem.cmi _build/src/core/opamProcess.cmi _build/src/core/opamFilter.cmi _build/src/core/opamSwitch.cmi _build/src/core/opamParallel.cmi _build/src/core/opamTypes.cmi _build/src/core/opamRepository.cmi _build/src/core/opamVariable.cmi _build/src/core/opamMisc.cmi _build/src/core/opamCompiler.cmi _build/src/core/opamVersion.cmi _build/src/core/opamFormat.cmi _build/src/core/opamFormula.cmi _build/src/core/opamGlobals.cmi _build/src/core/opamParser.cmi _build/src/core/opamLexer.cmi _build/src/core/opamLineLexer.cmi _build/src/repositories/opam-repositories.a _build/src/repositories/opam-repositories.cma _build/src/repositories/opam-repositories.cmxa _build/src/repositories/opamGit.cmi _build/src/repositories/opamDarcs.cmi _build/src/repositories/opamHg.cmi _build/src/repositories/opamLocal.cmi _build/src/repositories/opamVCS.cmi _build/src/repositories/opamHTTP.cmi _build/src/solver/opam-solver.a _build/src/solver/opam-solver.cma _build/src/solver/opam-solver.cmxa _build/src/solver/opamSolver.cmi _build/src/solver/opamHeuristic.cmi _build/src/solver/opamCudf.cmi _build/src/client/opam-client.a _build/src/client/opam-client.cma _build/src/client/opam-client.cmxa _build/src/client/opamPinCommand.cmi _build/src/client/opamAction.cmi _build/src/client/opamClient.cmi _build/src/client/opamConfigCommand.cmi _build/src/client/opamSwitchCommand.cmi _build/src/client/opamSolution.cmi _build/src/client/opamState.cmi _build/src/client/opamRepositoryCommand.cmi _build/src/client/opamArg.cmi
### stderr ###
# ...[truncated]
# Installed /home/phil/.opam/4.00.1/lib/opam/opamRepositoryCommand.cmi
# Installed /home/phil/.opam/4.00.1/lib/opam/opamState.cmi
# Installed /home/phil/.opam/4.00.1/lib/opam/opamSolution.cmi
# Installed /home/phil/.opam/4.00.1/lib/opam/opamSwitchCommand.cmi
# Installed /home/phil/.opam/4.00.1/lib/opam/opamConfigCommand.cmi
# Installed /home/phil/.opam/4.00.1/lib/opam/opamClient.cmi
# Installed /home/phil/.opam/4.00.1/lib/opam/opamAction.cmi
# Installed /home/phil/.opam/4.00.1/lib/opam/opamPinCommand.cmi
# ocamlfind: _build/src/client/opam-client.cmxa: No such file or directory
# make: *** [libinstall-with-ocamlbuild] Error 2

'opam install opam-lib' failed.
```

**Comment by pw374** [comment]
It's really weird: when I download/compile/install manually, the problem doesn't occur. o_O

**Comment by pw374** [comment]
so, opam reports `# ocamlfind: _build/src/client/opam-client.cmxa: No such file or directory`

but with a manual compilation I have this

```
/tmp/p/opam-1.1.1$ find . -name opam-client.cmxa
./_obuild/opam-client/opam-client.cmxa
```

I'm going to try on OS X...

**Comment by pw374** [comment]
I've just realised that with this PR, we won't be able to use OCaml 3.12. anymore.

**Comment by dsheets** [comment]
I can't seem to reproduce the build error with opam-lib with the same compiler. If this is an opam problem, we should file an issue in the opam tracker.

Is retaining 3.12 compatibility important? opam2web hasn't been 3.12 compatible for a long time (ever?). opam.ocaml.org requires 4.00.0+ to build.

**Comment by pw374** [comment]
On 15 Mar 2014, at 21:54 pm, David Sheets notifications@github.com wrote:

> I can't seem to reproduce the build error with opam-lib with the same compiler. If this is an opam problem, we should file an issue in the opam tracker.
> 
> On OS X it works fine as well.
> I don’t know where the problem comes from yet.

I’m going to try on the ocaml.org machine (in separate account though) to see if it works…

> Is retaining 3.12 compatibility important? opam2web hasn't been 3.12 compatible for a long time (ever?). opam.ocaml.org requires 4.00.0+ to build.
> 
> Well, the opam installation on ocaml.org uses the `system` switch, and as it’s a debian it means it’s ocaml.3.12.1.
> Apart from that, I don’t really care about the compatibility with 3.12 (actually, I do care, but not enough to ask anyone to give up on using the new nice features of ocaml).

**Comment by pw374** [comment]
So, it fails on ocaml.org as well, it's not a good sign...

http://pastebin.com/dc70FBzz (expires in 1 month)

I'm going to open an issue on opam-repository. (done: https://github.com/ocaml/opam-repository/issues/1789)

**Comment by pw374** [comment]
```
$ git clone https://github.com/pw374/opam-repository.git
[...]
$ opam remote remove default
[...]
$ opam remote add default opam-repository/
[...]
$ opam install opam-lib
[...]
$ opam install opam2web
The following actions will be performed:
 - install opam2web.1.3.1
1 to install | 0 to reinstall | 0 to upgrade | 0 to downgrade | 0 to remove

=-=-= Installing opam2web.1.3.1 =-=-=
opam2web.1.3.1 Downloading https://github.com/ocaml/opam2web/archive/1.3.1.tar.gz
Building opam2web.1.3.1:
  make
  make install PREFIX=/home/test/.opam/4.01.0
[ERROR] The compilation of opam2web.1.3.1 failed.
Removing opam2web.1.3.1.
  rm -f /home/test/.opam/4.01.0/bin/opam2web
  ocamlfind remove opam2web


===== ERROR while installing opam2web.1.3.1 =====
# opam-version 1.1.0
# os           linux
# command      make
# path         /home/test/.opam/4.01.0/build/opam2web.1.3.1
# compiler     4.01.0
# exit-code    2
# env-file     /home/test/.opam/4.01.0/build/opam2web.1.3.1/opam2web-16700-e7966f.env
# stdout-file  /home/test/.opam/4.01.0/build/opam2web.1.3.1/opam2web-16700-e7966f.out
# stderr-file  /home/test/.opam/4.01.0/build/opam2web.1.3.1/opam2web-16700-e7966f.err
### stdout ###
# ...[truncated]
# ocamlfind ocamlopt -c -bin-annot -g -package cmdliner -package opamfu.cli -package opam.client -package cow.syntax -package cow -syntax camlp4o -I apalog -o o2wTemplate.cmx o2wTemplate.ml
# ocamlfind ocamlopt -c -bin-annot -g -package cmdliner -package opamfu.cli -package opam.client -package cow.syntax -package cow -syntax camlp4o -I apalog -o opam2web.cmx opam2web.ml
# ocamlfind ocamlopt -linkpkg -g -package cmdliner -package opamfu.cli -package opam.client -package cow.syntax -package cow -syntax camlp4o apalog/compressed.cmx apalog/lexcombinedlog.cmx apalog/logentry.cmx apalog/readcombinedlog.cmx template.cmx o2wDocumentation.cmx o2wGlobals.cmx o2wMisc.cmx o2wStatistics.cmx o2wHome.cmx o2wPackage.cmx version.cmx o2wTemplate.cmx o2wUniverse.cmx opam2web.cmx -o opam2web.native
# + ocamlfind ocamlopt -linkpkg -g -package cmdliner -package opamfu.cli -package opam.client -package cow.syntax -package cow -syntax camlp4o apalog/compressed.cmx apalog/lexcombinedlog.cmx apalog/logentry.cmx apalog/readcombinedlog.cmx template.cmx o2wDocumentation.cmx o2wGlobals.cmx o2wMisc.cmx o2wStatistics.cmx o2wHome.cmx o2wPackage.cmx version.cmx o2wTemplate.cmx o2wUniverse.cmx opam2web.cmx -o opam2web.native
# File "_none_", line 1:
# Error: Files /home/test/.opam/4.01.0/lib/opam/opam-core.cmxa
#        and /home/test/.opam/4.01.0/lib/re/re.cmxa
#        make inconsistent assumptions over implementation Re
# Command exited with code 2.
# make[1]: Leaving directory `/home/test/.opam/4.01.0/build/opam2web.1.3.1/src'
### stderr ###
# fatal: Not a git repository (or any of the parent directories): .git
# fatal: Not a git repository (or any of the parent directories): .git
# fatal: Not a git repository (or any of the parent directories): .git
# make[1]: *** [opam2web.native] Error 10
# make: *** [build] Error 2

'opam install opam2web' failed.
$ 
```

I don't get this:
1. why are there "inconsistent assumptions over implementation Re"? I did `opam reinstall re` and it didn't change anything.
2. `fatal: Not a git repository (or any of the parent directories): .git` is it me or opam2web tries to build something while being installed? o_O
3. How can both 1. and 2. happen? whichever fails first should stop the process... But then the `fatal...` message happens (at least) 3 consecutive times...

**Comment by dsheets** [comment]
1. Did you install opam-lib from a pinned repository? Opam normally ships re.1.2.0 included with it but opam-lib should use the presently installed re. My guess is that you somehow have opam-lib installed with a bundled re but the switch re is 1.2.1 (newest).
2. That is quite strange. `opam2web.native` shouldn't be called during the installation process. Could you post the prior output to `stderr` from `/home/test/.opam/4.01.0/build/opam2web.1.3.1/opam2web-16700-e7966f.err` or turn on verbose?
3. There is some weirdness happening during the opam2web install. Nowhere is the built executable intentionally called.

**Comment by pw374** [comment]
1. I installed re.1.2.0 and it still fails... (same error)
2. there's actually nothing before on `stderr`! (installation output with verbose on: http://pastebin.com/yJCt6LQd)

**Comment by pw374** [comment]
I did that:

```
mv .opam .opam-old
opam init default ~/opam-repository
opam switch 4.01.0
yes | opam install opam2web re.1.2.0
```

and still have the same error... :(

**Comment by dsheets** [comment]
1. The re error is the real error. How did you install `opam-lib`? Is it pinned? What does `ocamlobjinfo` say about those two files?
2. The git errors are due to the versioning system trying to inspect the repository to determine the commit being built. I will send a patch to opam-repository soon to fix this issue.

**Comment by dsheets** [comment]
The issue appears to be with ocaml/opam-repository#1790. The non-ocamlbuild build system does not query findlib for linking and instead links the re dependency in directly. This causes both the opam-core and the re lib to expose an implementation of `Re`. 

Could you post the full log of the original erroring build that prompted the switch in the opam-lib build sequence?

**Comment by pw374** [comment]
On 16 Mar 2014, at 15:18 pm, David Sheets notifications@github.com wrote:

> The issue appears to be with ocaml/opam-repository#1790. The non-ocamlbuild build system does not query findlib for linking and instead links the re dependency in directly. This causes both the opam-core and the re lib to expose an implementation of Re.

That makes sense.

> Could you post the full log of the original erroring build that prompted the switch in the opam-lib build sequence?

cf. https://github.com/ocaml/opam-repository/pull/1790#issuecomment-37759856

**Comment by dsheets** [comment]
Unfortunately, I can't pinpoint where the non-ocamlbuild system is failing and `ocamlobjinfo` doesn't appear to list `Re` for `opam-core.cmxa`. The hashes seem to match. Maybe that error is an ocp-build problem? I'm more inclined to attempt to fix the ocamlbuild version, though.

**Comment by AltGr** [comment]
@pw374 I recently added more detailed information on the build system(s) at https://github.com/ocaml/opam#compiling-this-repo
If you run `make; make libinstall` within OPAM it will install a version of opam-lib bundled with its own dependencies, which is likeky to get you into trouble, so that may have been the problem here. `make distclean; ./configure; make prepare; make compile; make libinstall` to get back to opam-lib using external dependencies.

**Comment by dsheets** [comment]
Is it possible to integrate now?

**Comment by pw374** [comment]
I'm currently integrating (so I stopped the automatic building of ocaml.org, and will re-start it again once everything's installed). BTW, thank you @dsheets for this PR :)

**Comment by pw374** [comment]
It's now running :)

**Comment by dsheets** [comment]
Hooray! Thanks @pw374 @AltGr!

**Pull request merged**
