### PR TITLE
Issue #90

### PR DESCRIPTION
**Pull request by voila**
I've added 4 missing pages in tutorials: hashtbl.html, set.html, map.html, comparison_standard_containers.html.

I've copied them from http://mirror.ocamlcore.org/ocaml-tutorial.org/.

### CODE REVIEW

**Comment by agarwal** [comment]
These are not listed on the frontpage of that website. How did you find
them? Are we perhaps missing more still?

**Comment by agarwal** [comment]
I missed your reference to #90. I see you found these from the broken
links. Maybe we can see the full contents of the mirror directly on the
server by contacting Sylvain.

**Comment by voila** [comment]
Some of the broken links seems to be related to content coming from http://mirror.ocamlcore.org/ocaml-tutorial.org/, I assumed the way to go about this was to add the missing pages to ocaml.org. 
Was that the right thing to do ?

**Comment by agarwal** [comment]
Yes, that's great! There are several more it seems.

**Comment by voila** [comment]
Yes, they are easy to fix. Some others are more tricky (external content which has disappeared), we'll have to agree on how to fix these...

**Comment by agarwal** [comment]
Hi Sylvain,

Any chance we can get a tarball of the ocaml-tutorial mirror? We've noticed
many tutorials are missing from the main list [1]. Some have been tracked
down by following broken links, but maybe we're still missing some. We
could make sure by looking at a complete tarball.

[1] http://mirror.ocamlcore.org/ocaml-tutorial.org/index.html

Thanks.

**Pull request merged**
