### PR TITLE
added /usr/lib/ocaml

### PR DESCRIPTION
**Pull request by haytham-med**
clarify location of the standard library

### CODE REVIEW

**Comment by pw374** [comment]
But it's not always in that place...

**Comment by agarwal** [comment]
Maybe you'd like to link to the files on github, e.g. [set.ml](https://github.com/ocaml/ocaml/blob/trunk/stdlib/set.ml).

**Comment by haytham-med** [comment]
pw374, isn't it always in this location in linux?

**Comment by pw374** [comment]
Nope. It's pretty trivial to make a Linux distribution that installs it elsewhere.

Philippe Wang
(mail sent from a phone)

**Comment by pw374** [comment]
Good idea, in my opinion.

Philippe Wang
(mail sent from a phone)

**Comment by Chris00** [comment]
Fixed following @agarwal 's suggestion.

**Pull request closed without merging**
