### PR TITLE
make the installation options findable on the page

### PR DESCRIPTION
**Pull request by mk270**
should go some way to resolving #74

### CODE REVIEW

**Comment by Chris00** [comment]
Your purpose is no clear to me.  You remove a bunch of information but do not propose to put them elsewhere.  I do not understand for example why you remove the link to the licence.

**Comment by mk270** [comment]
Ok, so I _literally_ did not find most of the content on the page, the first seven or eight times I looked at it, and only discovered it by accident when browsing the revision log.

Here's a screenshot of what it looks like on my screen: http://mk.ucant.org/media/screenshot.jpg

That's in 1280x800 on a normal laptop.

So, I tried to remove information which a user didn't need to know to install OCaml: previous versions, what is new in the _current_ version(!), the licensing arrangements (which they can consult at their own initiative if so inclined), and a bunch of adverts for alternative Javascript targets. This stuff really just is not that important - it can be linked from other pages: the installation are complicated enough by themselves without having two non-installation boxes on the right hand side about the latest features and the terms under which you can redistribute the compiler.

**Comment by mk270** [comment]
In case it wasn't clear: removing some of the information above the tabs meant that the information below the menu bar was now visible, meaning it got noticed. A bunch of tabs at the bottom of the page was something I mistook for boilerplate rather than content.

**Comment by mk270** [comment]
Ok, so it seems the licence and the advertisement for the BSD licensing arrangement aren't present elsewhere on the site(!) .. I didn't realise this

**Comment by mk270** [comment]
Ok, I've re-added the licensing info - had assumed it was duplicated elsewhere

**Comment by agarwal** [comment]
Thanks for the input. I see your point. The tabs are the main content but
not very prominent. This page has mixed up two separate items: listing the
releases available, and providing installation instructions. Let's do this:
- Create a new Releases page, which is related to Issue #39 and partially
  undoes commit 2fda77b972002e684f244211237ccc2081ba90a0.
- Simplify the opening text as Martin proposed, moving text about different
  releases to the above page. I don't want to just delete the text;
  js_of_ocaml, ocamljava, and older releases should be mentioned somewhere.
- Move the licensing link to the new page too. The license is too important
  to be only in the FAQ.
- With that done, we can again look at the Install page and decide if the
  tabs are worth it. It maybe better just as flat text with headers and
  sub-headers. A table of contents can be auto-generated (e.g.
  http://ocaml.org/taste.html), which might be even more clear than the tabs.

**Comment by Chris00** [comment]
On Sat, 22 Dec 2012 11:57:54 -0800, Ashish Agarwal wrote:

> Thanks for the input. I see your point. The tabs are the main
> content but not very prominent. This page has mixed up two separate
> items: listing the releases available, and providing installation
> instructions. Let's do this: [...]

I meant to reply something similar.  I agree with these points — we do
not have to loose information for readability, we want both!

**Comment by mk270** [comment]
Ok, is that better?

**Comment by agarwal** [comment]
Looks good. I've merged all your changes.

**Pull request merged**
