### PR TITLE
Add anchors to FAQ page so they are externally linkable

### PR DESCRIPTION
**Pull request by tekknolagi**
This makes it easy for people to link to specific official explanations of topics like arbitrary precision arithmetic.

### CODE REVIEW

**Comment by Chris00** [comment]
The HTML generated from Markdown already define anchors from the title, for example for [arbitrary precision arithmetic](https://ocaml.org/learn/faq.html#Isitpossibletodocomputationswitharbritraryprecisionarithmetics).  Maybe it is too much work to retrieve the URL and a small "copy this link' icon would be welcome?

**Comment by tekknolagi** [comment]
Oh! I did not realize that. Wow, I really should have checked. I think that is a great idea. Where is the template that I should modify to add that?

**Comment by Chris00** [comment]
I'm afraid modifying a template won't be enough.  It can possibly made part of [`omd`](https://github.com/ocaml/omd) through an option (@pw374, any thoughts?) or achieved by post-processing.

**Comment by pwbs** [comment]
So, we want to generate a button with a "copy this link" function? It shouldn't be hard to do...

**Comment by Chris00** [comment]
@pwbs Any development on this?

**Comment by XVilka** [comment]
@tekknolagi ping?

**Comment by avsm** [comment]
I'll go ahead and close this as it's not progressing, and there is a new version of omd out (#1321), so this could be addressed in a future iteration of the site.

**Pull request closed without merging**
