### PR TITLE
Doc page improvements

### PR DESCRIPTION
**Pull request by dbuenzli**
I removed random chit-chat that is of little use to the newcomer and mention `odig`.

### CODE REVIEW

**Comment by dbuenzli** [comment]
It seems the changes didn't make it online.

**Comment by pw374** [comment]
indeed... And for some reasons that are out of my reach, I can't ssh to the server!

CC @Chris00, @agarwal

**Comment by dbuenzli** [comment]
Ah ok thanks ! I thought the updates were automated on merge.

**Comment by pw374** [comment]
They are expected to be automatic. I was trying to ssh the server with the intention of figuring out what was going wrong...

**Comment by Chris00** [comment]
On 2016-10-03, Philippe Wang wrote:

> indeed... And for some reasons that are out of my reach, I can't ssh 
> to the
> server!

Looking into it.

**Comment by Chris00** [comment]
Doing by hand the same as the script updated the page.  Have to look more into it.
@pw374 If you want access, send me your public ssh key.

**Comment by pw374** [comment]
> @pw374 If you want access, send me your public ssh key.

Done, as sometimes it can be useful. :)

**Comment by Chris00** [comment]
On 2016-10-03, Philippe Wang wrote:

> They are expected to be automatic.

This is supposed to be fixed.

**Pull request merged**
