### PR TITLE
Fix Footer width on mobile #1237

### PR DESCRIPTION
**Pull request by Shubham-Vishwakarma**
Footer width on mobile #1237

### CODE REVIEW

**Comment by Shubham-Vishwakarma** [comment]
Changing pull request to master

**Comment by patricoferris** [comment]
cc @avsm: this LGTM

**Comment by avsm** [comment]
Many thanks for your contribution @Shubham-Vishwakarma! This has been pushed to the `staging` branch and will appear shortly on https://staging.ocaml.org/ as a preview. If you could verify your fix appears correctly there with a comment here, we can merge this PR and have it go live.

**Review by avsm — APPROVED** [review]

**Comment by Shubham-Vishwakarma** [comment]
@avsm  I can see my changes

**Comment by avsm** [comment]
Thank you for the contribution! Now live.

**Pull request merged**
