### PR TITLE
Update front page and create 4.13.1 releage page

### PR DESCRIPTION
**Pull request by Octachron**
This PR adds a release page for 4.13.1, updates the list of releases and the date of the last version of OCaml, and comments out the OCaml workshop announce in News on the frontpage.

### CODE REVIEW

**Comment by Octachron** [comment]
I have added an updated Change notes too.

**Comment by patricoferris** [comment]
Ah, this came in just after I PR-ed #1612 but now we can just use the latest opam-repository commit. @Octachron could you bump the repository commits in the Dockerfiles in this PR to the latest opam-repository commit (or at least one that comes after 4.13.1 was released) please? We need to do that because of how we learn of the latest release https://github.com/ocaml/ocaml.org/blob/eca0b931985ca4cf5c646224c2292e53a0d73604/Makefile.common 

Without this https://ocaml.org/releases/latest goes to 4.12.0 :))

**Comment by Octachron** [comment]
Bumped. Sorry, I should have done that earlier, but I had switched on non-release tasks during last week.

**Review by patricoferris — APPROVED** [review]
Thanks! Once CI is happy should be good for merging :))

**Comment by patricoferris** [comment]
Thanks again :))

**Pull request merged**
