### PR TITLE
Corrected Bloomberg Finance L.P. to Bloomberg L.P.

### PR DESCRIPTION
**Pull request by StefPac**
This pull request changes the company name displayed from Bloomberg Finance L.P. to Bloomberg L.P.

### CODE REVIEW

**Comment by amirmc** [comment]
I can see both Bloomberg LP and Bloomberg Finance LP used in the wild.  e.g see the copyright notice at the bottom of the following pages.
- http://www.bloomberg.com
- http://www.bloomberg.com/professional/

**Comment by StefPac** [comment]
Amir, in this case Bloomberg L.P. is the writing to be used. Thanks!

**Comment by amirmc** [comment]
Works for me. Thanks for the pull request! Will be live in few mins.

**Comment by amirmc** [comment]
Sorry for accidentally closing. Hit the the wrong button on the mobile UI. :)

**Comment by agarwal** [comment]
@amirmc Why was closing this issue a mistake? You merged the pull request, so I think it is done.

**Comment by amirmc** [comment]
I was using my phone and hit the 'comment & close' button instead of the 'comment' button.  Then I had to reopen the PR in order to do the merge (which then automatically closes the PR).  

I was apologising for my ineptitude since each of those actions would have fired off emails to folks in the thread :)

**Comment by agarwal** [comment]
My mistake... I thought in the end the issue was still open, and was asking you to close it... but it already was.

**Pull request merged**
