### PR TITLE
Update teaching-ocaml.md

### PR DESCRIPTION
**Pull request by grayswandyr**
Added course at ISAE/Supaéro.

### CODE REVIEW

**Comment by amirmc** [comment]
Thank you!  Is this also on the [map](https://www.google.com/maps/d/edit?mid=zk8_K4G_usic.kkzYvEvqV44Q)?

**Comment by amirmc** [comment]
I'll add it to the map now.

**Comment by grayswandyr** [comment]
Le 27/11/2014 14:01, Amir Chaudhry a écrit :

> I'll add it to the map now.

Thanks, I would have needed a Google account I guess. Too bad 
OpenStreetMap wasn't used.

best

david

**Comment by amirmc** [comment]
I'm sure we'd be perfectly happy to switch to OSM maps but some of us are not as familiar with it.  It might even be easier to automate with the appropriate libraries.  

I've opened a new issue, #596, to track this. Would be great to have more contributors and this seems like a useful, self contained item.

**Pull request merged**
