### PR TITLE
Update up_and_running.md

### PR DESCRIPTION
**Pull request by ac27182**

### CODE REVIEW

**Comment by johnwhitington** [comment]
Is this new behaviour in a new dune version, or was `up_and_running.md` always wrong?

**Comment by ac27182** [comment]
I'm new to the OCaml ecosystem so don't know whether or not it's specific to this particular release of dune.

For context, I wanted to run the executable in my terminal emulator without running `dune exec ./helloworld.exe`

I went hunting for it in the `_build` directory and found the executable in the `default` subdirectory

```
$ tree -L 3
.
├── _build
│   ├── default
│   │   ├── dune
│   │   ├── dune-project
│   │   ├── helloworld.exe
│   │   ├── helloworld.ml
│   │   └── notes.md
│   └── log
├── dune
├── dune-project
├── helloworld.ml
└── notes.md
```

I thought for a new starter it would me more helpful to be explicit as to where the executable is.

What are your thoughts?

**Comment by johnwhitington** [comment]
Oh, I have no idea either. I wrote the original up and running page, and I was just interested to see if I'd made a mistake.

I don't use Dune day-to-day.

So, I think your patch is fine, but let's wait for someone who knows Dune to jump in.

**Review by avsm — APPROVED** [review]
This has always been how dune works. There is a [dune workspace](https://dune.readthedocs.io/en/stable/dune-files.html#dune-workspace) associated with every build, and `default` is the (you guessed it) default one. 

Thanks for the PR @ac27182! Merging to the live site.

**Comment by ac27182** [comment]
Thank you both! @avsm @johnwhitington

**Pull request merged**
