### PR TITLE
Made the sizes of the book images in the books and paper section equal

### LINKED ISSUE #1344: Improve Books and Paper section in https://ocaml.org/docs/ on screen sizes less than 768px
On screen sizes less than 768px, the sizes of the book images are not equal. I'd like to improve that section by making the first book image be the same size as the last two.

image

### PR DESCRIPTION
**Pull request by TildaDares**
# Issue Description

On screen sizes less than 768px, the sizes of the book images are not equal.

## Before

image

Fixes #1344 

## Changes Made

Added a class that sets the sizes of the book images to a fixed width on screen sizes less than 768px.

## After

image

* **Please check if the PR fulfills these requirements**

- [x] PR is descriptively titled and links the original issue above
- [x] Before/after screenshots (if this is a layout change)
- [ ] Details of which platforms the change was tested on (if this is a browser-specific change)
- [ ] Context for what motivated the change (if this is a change to some content)

### CODE REVIEW

**Comment by gs0510** [comment]
Thanks for your PR @TildaDares! The image for Real World OCaml looks very pixelated, can you lower the size of all images rather than increasing it? Thanks!

**Comment by TildaDares** [comment]
@gs0510 Can I look for an image of that book cover that isn't pixelated? Even with the small size it still looks pixelated.

**Comment by gs0510** [comment]
Thanks @TildaDares! This LGTM :)

**Comment by avsm** [comment]
Nice work @TildaDares! Pushed to the live site :)

**Comment by TildaDares** [comment]
Thank you @avsm.

**Pull request merged**
