### PR TITLE
replaced stockimage by hand-drawn header image

### PR DESCRIPTION
**Pull request by Iix**
According to #953 I redrew the header image, which can be used with CC-BY-SA 4.0
The respective SVG file can be found [here](https://github.com/mirage/mirage-propaganda)

### CODE REVIEW

**Comment by agarwal** [comment]
Hi. Apologies but I think this doesn't follow the intention of the community consensus on our licenses. The intention wasn't just that the particular file that currently exists shouldn't be used elsewhere, but rather that the general look and feel of the site shouldn't be used elsewhere. IMHO redrawing the identical image again doesn't allow altering the license it is released under.

**Comment by Iix** [comment]
Hi @agarwal 
How can the license issue be satisfied then? The [current image](https://github.com/ocaml/ocaml.org/blob/master/site/img/header.jpg) is [mirrored twice vertically](https://github.com/ocaml/ocaml.org/commit/87c01eededa781a52674e0b660f7a1db2f30ac75) in a very sloppy way, which IMHO is enough reason to replace the existing one.

**Comment by agarwal** [comment]
@lix Can you please confirm your goal. Where exactly do you want to use this banner image?

**Comment by Iix** [comment]
@agarwal I was informed by a member of the mirage team that the [current image](https://github.com/ocaml/ocaml.org/blob/master/site/img/header.jpg) had 0) a license issue and 1) an issue with the vertical mirroring and, - hence, - needed to be redrawn to be used as a header image for the current ocaml.org website.

**Comment by agarwal** [comment]
Apologies. I suspect I've been misunderstanding. Above I said this image "shouldn't be used elsewhere" and in issue #953, which you referenced, I said "it would be odd for _other_ websites" to use the image. If you are improving the image for purposes of use on ocaml.org itself, then there is no problem! Rather, we thank you for the work.

To be clear, your comment "I redrew the header image, which can be used with CC-BY-SA 4.0" would **not** apply. Your contribution of this new image does not allow the license to change. Please confirm that you allow your contribution to be licensed under the existing terms of the ocaml.org project.

Also, since I feel I'm missing something, can you please confirm that you do **not** want to use this image on another website.

Thanks.

**Comment by Iix** [comment]
@agarwal no worries, obviously, there was a misunderstanding or I was unwell informed. My intention indeed was to liberate the header image, - I was informed it was an image copyrighted by stock image provider, - from any license, hence I chose CC-BY-SA, as discussed with @mato to be used for [mirage-propaganda](https://github.com/Iix/mirage-propaganda).

Let me know how or what you want me to change so the image can be used for the [ocaml.org](https://ocaml.org) website *exclusively* 😎

You're welcome!

**Comment by agarwal** [comment]
> to be used for mirage-propaganda.

Sorry but this comment leaves me confused again. It sounds like you do want to use this image somewhere else (since to my knowledge the mirage-propaganda repo is not for the ocaml.org project).

To accept this PR, I need you to reply "yes" to both of the following questions:

1. Do you agree to have your contribution licensed under the terms of the ocaml.org licenses? In particular the image you are providing in this PR would be owned by the ocaml.org project.

2. Do you acknowledge that the ocaml.org project will have exclusive rights to use this image? In other words, you do **not** have the right to use this image anywhere else.

**Comment by wokalski** [comment]
@agarwal Why would you make such choices? Is there any good reason not to make the contents of this website as open as possible? If yes, can those sub parts be licensed separately?

**Comment by Chris00** [comment]
@wokalski I think @agarwal explained it above: _the intention is ... that the general look and feel of the site shouldn't be used elsewhere_ so that ocaml.org keeps a visual identity.  The _content_ is very open, see [LICENSE.md](https://github.com/ocaml/ocaml.org/blob/master/LICENSE.md).

**Comment by wokalski** [comment]
@Chris00 Thank you for your answer. I am failing to understand under what circumstances somebody would copy _the general look and feel of the site_. Even if it happened, how would it hurt anyone? Last but not least, I don't think it's reasonable to lose even one contribution because of such arbitrary constraint.

**Comment by Chris00** [comment]
> I am failing to understand under what circumstances somebody would copy the general look and feel of the site.

Well, that has been a problem in the past...

> I don't think it's reasonable to lose even one contribution because of such arbitrary constraint.

From another point of view, why not simply donate the image to the ocaml.org if one indeed desires to improve the project?  As @agarwal said, contributions are highly appreciated — but the licenses are there for a reason.

**Comment by wokalski** [comment]
I respect your rules but I don't think there's anything bad that could happen to the project or anyone even if someone decided to copy the look of the site. Many libraries and languages use the same boilerplates and it doesn't seem to be a problem for them.

> From another point of view, why not simply donate the image to the ocaml.org if one indeed desires to improve the project?

Because one might want to use an image they created in their free time and for nothing in return somewhere else.

**Comment by Chris00** [comment]
> one might want to use an image they created in their free time and for nothing in return somewhere else.

What for?  If the image was not on ocaml.org, he would not have copied it in the first place.

The maintainers of ocaml.org also put hundreds of hours in the site for nothing in return...  And it is not because we wanted to reuse the work we put in here for something else...

**Comment by wokalski** [comment]
> What for?

For instance for an article on the web to have a nice background image.

> The maintainers of ocaml.org also put hundreds of hours in the site for nothing in return... And it is not because we wanted to reuse the work we put in here for something else...

Putting artificial value of your work __for the community__ higher than __the community__  itself is really ironic. I find this artificial set of values very disappointing.  Especially that this website just begs for improvements because it's in a terrible shape and is definitely subpar to the product it advertises.

This discussion reached a dead point.

**Comment by Chris00** [comment]
> Putting artificial value of your work for the community higher than the community itself is really ironic.

Not trying to put any “artificial value” in our work here but rather pointing out that we are not asking anything we did not do ourselves.

**Comment by agarwal** [comment]
> @agarwal Why would you make such choices?

To be clear, _I_ didn't make this choice. It was reached by community consensus. I'm only communicating what that decision was and assuring we adhere to it.

> Especially that this website just begs for improvements because it's in a terrible shape and is definitely subpar to the product it advertises.

I agree, but nothing prevents anyone from improving _this_ site.

Branding other sites related to ocaml is supported, just not with this specific banner image. People are free to use the [ocaml-logo](https://github.com/ocaml/ocaml-logo)s.

**Comment by wokalski** [comment]
> It was reached by community consensus

I understand. Could you disclose who is the community? The OCaml compiler contributors? Do you think the community could reconsider it?

> nothing prevents anyone from improving this site.

I'm making a case that restrictive licensing does prevent people from improving the design of this site because they cannot reuse their work on another site which I would argue is counter productive.

**Comment by agarwal** [comment]
> Could you disclose who is the community?

I'm not qualified to answer technically. Our previous way of saying "the community agreed to foo" was if the discussion happened on the OCaml Mailing List, and it was rather clear that "most" people want "foo". Also see the [About](http://ocaml.org/about.html) page, which provides some information on governance of the site.

**Comment by agarwal** [comment]
Related discussion: https://discuss.ocaml.org/t/ocaml-org-licensing/2036.

I'll close this PR without merging since I didn't receive the required affirmative responses to the 2 questions posed on April 4th.

**Pull request closed without merging**
