### PR TITLE
Korean translation update

### PR DESCRIPTION
**Pull request by seungjin**
Two letter English(Roman Alphabet) abbreviation to its native language(Korean).

### CODE REVIEW

**Comment by agarwal** [comment]
I'm accepting this patch though I don't know Korean. @seungjin Thanks for your contributions. Perhaps you can explain a couple of points:
- In several places you replaced 기본기 with 기본사항. Can you explain why?
- You added large pieces of English in some places. Are you planning to incrementally convert that to Korean?

Thanks.

**Comment by agarwal** [comment]
Sorry, it was of course already merged, so I just meant to ask the questions.

**Comment by seungjin** [comment]
- 기본기(previous one) and 기본사항(newer one) can be the same meaning. But the previous one is more like "basic skill" and the newer one is "basic information". For example, we mostly use 기본기(previous one) for meaning the "basic" skill of martial art. So I changed to more general term that sound about right for the context. 
- Yes, I am planing and doing translation those to English when I get free time.

**Comment by agarwal** [comment]
@seungjin Thanks for the answers!

**Pull request merged**
