### PR TITLE
Update structure_of_ocaml_programs.md

### PR DESCRIPTION
**Pull request by bowsersenior**
Make docs for 3rd snippet consistent with code

### CODE REVIEW

**Comment by samoht** [comment]
Thanks!

**Comment by sanette** [comment]
on the other hand the text is not completely exact. In fact the `let ()=` does check that the result is indeed `()`.

**Comment by samoht** [comment]
hum indeed, maybe I've merged that one too quickly. @sanette do you think I should revert this change? (`let () =` is used as-is just after, so I think that's ok)

**Comment by pw374** [comment]
I think this should be reverted indeed.

because "_but throw away the result_"  makes sense only with `let _ =` (it doesn't with `let () =`)

**Comment by pw374** [comment]
I reverted that merge :)

**Comment by pw374** [comment]
https://github.com/ocaml/ocaml.org/pull/1125/files#diff-c7075d3266aa322ac73a724bb06e6924L543

To achieve consistency, it's the `let () =` from the "3rd code snippet" that should've been changed to `let _ =`

**Comment by bowsersenior** [comment]
Thanks for the comments. I opened a [new PR](https://github.com/ocaml/ocaml.org/pull/1157) that updates the 3rd snippet instead.

**Pull request merged**
