### PR TITLE
Added advanced functional programming course at UPD

### PR DESCRIPTION
**Pull request by rdicosmo**

### CODE REVIEW

**Comment by amirmc** [comment]
Thanks! I wonder if we should add the MOOC to this list too...

**Comment by rdicosmo** [comment]
Thanks Amir,
       I'm trying indeed to make a proposal to add the MOOC,
waiting for the dependencing to make the site to come in...
if I get into trouble, I'll ask for help :-)

On Fri, Aug 14, 2015 at 07:14:42AM -0700, Amir Chaudhry wrote:

> Thanks! I wonder if we should add the MOOC to this list too...
> 
> —
> Reply to this email directly or view it on GitHub.*

## 

Roberto Di Cosmo

---

Professeur               En delegation a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann  
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo

## FRANCE.                  Twitter: http://twitter.com/rdicosmo

Attachments:
MIME accepted, Word deprecated

##       http://www.gnu.org/philosophy/no-word-attachments.html

Office location:

Bureau 3020 (3rd floor)
Batiment Sophie Germain
8 place Aurélie Nemours

## Metro Bibliotheque Francois Mitterrand, ligne 14/RER C

GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by amirmc** [comment]
I just saw your message!  I've already submitted a PR to add a link from the front page (#685).

**Comment by rdicosmo** [comment]
Cool, thanks, you were faster than me :-)

On Fri, Aug 14, 2015 at 07:29:23AM -0700, Amir Chaudhry wrote:

> I just saw your message! I've already submitted a PR to add a link from the
> front page (#685).
> 
> —
> Reply to this email directly or view it on GitHub.*

## 

Roberto Di Cosmo

---

Professeur               En delegation a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann  
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo

## FRANCE.                  Twitter: http://twitter.com/rdicosmo

Attachments:
MIME accepted, Word deprecated

##       http://www.gnu.org/philosophy/no-word-attachments.html

Office location:

Bureau 3020 (3rd floor)
Batiment Sophie Germain
8 place Aurélie Nemours

## Metro Bibliotheque Francois Mitterrand, ligne 14/RER C

GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Pull request merged**
