### PR TITLE
Add a "News" navbar button.

### PR DESCRIPTION
**Pull request by pmetzger**
Add a "News" navbar button pointing to community/planet.

Note that this change is completely untested, I couldn't get the web site building on my machine and I simply did a mechanical copy of the existing navbar elements.

However, the change is also trivial so someone should be able to figure it out easily if it's broken.

### CODE REVIEW

**Comment by agarwal** [comment]
I'm personally okay to merge this, but I'm unsure how others feel. The current content of the site is divided into 4 categories: Learn, Documentation, Packages, and Community. The navbar represents these 4 sections. Is _News_ so important that it should be also be added? If that, why not _Install_, _Books_, _Manual_, etc? Is _News_ more important than these?

**Comment by Drup** [comment]
> Is News so important that it should be also be added?

Yes.

> If that, why not Install, Books, Manual, etc? Is News more important than these?

Those have barely changed in 5 years, unlike "News". OCamlers might want to consult and access the planet page regularly and easily. Not the book page.

**Comment by Chris00** [comment]
Thanks

**Comment by agarwal** [comment]
Ok, thanks for explaining why News is special. @Chris00, thanks for merging it.

**Pull request merged**
