### PR TITLE
fix: download link missing from the releases page

### PR DESCRIPTION
**Pull request by meenal06**
fixes #https://github.com/ocaml/ocaml.org/issues/1215

- I have added a download link for each of the releases as requested.

### CODE REVIEW

**Comment by meenal06** [comment]
Hi @avsm can you please review this pull request?

**Comment by patricoferris** [comment]
Hi @meenal06 thanks for the contribution :))

A few points. I believe in the original issue you linked to we decided to use the Github releases as the download links (at least for the compilers that have them). You will need to check the individual pages to work out which ones are on there and which aren't.

In addition to this, there's also a french page that needs updating with the same information https://ocaml.org/releases/index.fr.html -- I believe the french word is téléchargé.

**Comment by avsm** [comment]
Confirmed -- the caml.inria.fr site is deprecated, so the download links need to match the 'source tarball' on the linked page. For example, see https://ocaml.org/releases/4.10.2.html for the source tarball link for the 4.10.2 release.

**Comment by meenal06** [comment]
@avsm @patricoferris  I have done the requested changes ,please have a look

**Review by avsm — APPROVED** [review]
Diff looks good, and now merged to live. Thanks for the contribution!

**Pull request merged**
