### PR TITLE
Paragraph linking to the new Discourse-based forum discuss.ocaml.org.

### PR DESCRIPTION
**Pull request by mjambon**
English + about the same in French.
Note that I'm mentioning it's ok to create categories in other languages than English.

The goal of this edit is to drive new users to the new forum. Feel free to rewrite the whole thing.

### CODE REVIEW

**Comment by mjambon** [comment]
Please note that I didn't preview the page. I installed the required packages, but then I gave up at:
```
martin@mj2 [new-forum] ~/dev/friends/ocaml.org $ make
make staging SET_STAGING='-set staging'
make[1]: Entering directory '/mnt/ssd/shared/dev/friends/ocaml.org'
cd script && \
ocamlfind ocamlopt -annot -g -safe-string -o ../"script/generate_opam_update_list" -package opamfu,opam2web,cow \
  -linkpkg generate_opam_update_list.ml
File "generate_opam_update_list.ml", line 28, characters 4-9:
Error: Unbound value H.tag
Makefile.common:40: recipe for target 'script/generate_opam_update_list' failed
make[1]: *** [script/generate_opam_update_list] Error 2
make[1]: Leaving directory '/mnt/ssd/shared/dev/friends/ocaml.org'
Makefile:4: recipe for target 'local' failed
make: *** [local] Error 2
```

**Comment by objmagic** [comment]
Thanks for the effort. Can we make the change on front page (http://ocaml.org/)? For example, change "Chat live with OCaml experts!" to https://discuss.ocaml.org/? (https://github.com/ocaml/ocaml.org/blob/master/site/index.md)

**Comment by mjambon** [comment]
@objmagic I added you as a collaborator, so you can edit my branch at https://github.com/mjambon/ocaml.org/tree/new-forum if you want to add something simple to this PR.

**Comment by objmagic** [comment]
@mjambon Thanks. Let me first try building up the site...

**Comment by Chris00** [comment]
@mjambon Did you install deps with `make deps` (after an `opam update`)?

**Comment by mjambon** [comment]
@Chris00 no. The readme says:
```
BUILD
=====
The site consists only of static pages, so it can be built and run
entirely on a local machine without dependencies on external file or
database servers. Simply run:

    make
```

Now, running `make deps` gives me:
```
The following dependencies couldn't be met:
  - ocamlorg -> cow >= 2.2.0
  - ocamlorg -> opam2web >= 1.4.0 -> cow < 2.0.0
Your request can't be satisfied:
  - Conflicting version constraints for cow

No solution found, exiting
```

I am not going to build the site. This would be a very poor use of my time or any contributor's time.

**Comment by Chris00** [comment]
On 2017-07-06, Martin Jambon wrote: 
> 
> BUILD ===== The site consists only of static pages, so it can be built 
> and run entirely on a local machine without dependencies on external 
> file or database servers. Simply run: 
> 
>     make 

Right but that section comes right after one entitled “DEPENDENCIES”...

> Now, running make deps gives me:
>
> The following dependencies couldn't be met:
>   - ocamlorg -> cow >= 2.2.0
>   - ocamlorg -> opam2web >= 1.4.0 -> cow < 2.0.0

I’m surprised because opam2web ≥ 1.5.0 says `"cow" {>= "2.2.0"}`.  @AltGr  ?

I pushed a change that should solve that (I’m glad if you confirm that it works).

**Comment by objmagic** [comment]
I am on OS X 10.12.5, 4.03.0 switch, latest master, and see the dependency error message

```
ocaml.org (master) $ opam pin add ocaml.org . --y
[NOTE] Package ocaml is already path-pinned to OCaml/ocaml.org.
       This will erase any previous custom definition.
Proceed ? [Y/n] y

[ocaml] OCaml/ocaml.org/ synchronized
[ocaml] Installing new package description from OCaml/ocaml.org

ocaml needs to be installed.
The following dependencies couldn't be met:
  - ocaml -> opam2web >= 1.5.0
Your request can't be satisfied:
  - No package matches opam2web>=1.5.0.

No solution found, exiting
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

**Comment by Chris00** [comment]
> Your request can't be satisfied:
>  - No package matches opam2web>=1.5.0.

You need to make sure your opam repository is [up to date](http://opam.ocaml.org/packages/opam2web/).

**Comment by Chris00** [comment]
@objmagic I've [updated](https://github.com/ocaml/ocaml.org/commit/dd4c3b9bde1f82f10e9d8ccd0d4078b7ed9a96e3) the link on the front page.

**Comment by agarwal** [comment]
It would make sense to also update `community/index.html`. It lists 4 mailing lists directly, but we should bump one off and replace it with `discuss.ocaml.org`.

**Pull request merged**
