### PR TITLE
Travis: Pin opam2web for the compilation to succeed

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
Argh, I meant to see whether this was fixing the builds...

**Comment by Chris00** [comment]
The docker cloud is useless to me as I cannot see the error (login required).  @avsm ?

**Comment by pw374** [comment]
I thought it'd be useful to merge it to see if it's indeed fixing the builds, since if it was broken, it won't do much harm and worst case scenario we can revert...

**Comment by Chris00** [comment]
On 2017-05-31, Philippe Wang wrote:
>
> I thought it'd be useful to merge it to see if it's indeed fixing the 
> builds, since if it was broken, it won't do much harm and worst case 
> scenario we can revert...

I restarted the Travis build and it was indeed the culprit.  So it was 
fine! ☺

**Pull request merged**
