### PR TITLE
Change breadcrumb position and differentiate languages

### LINKED ISSUE #1378: Repositioning of breadcrumbs on non top level pages and differentiate languages
I suggest we move the breadcrumbs to the right of the page and also differentiate the languages

Capture

bfore

If it's a good issue, I can make the fix

### PR DESCRIPTION
**Pull request by dinakajoy**
# Issue Description
On pages with  left sidebar,  the breadcrumbs appear on the middle of the page which isn't a good user experience as users are used to seeing breadcrumbs on the left side of the page. Also the language are clustered and difficult to differentiate. This can confuse users on which one to select.

Fixes #1378 

This PR positions the breadcrumbs on the left side of the page
  
Before
before-breadcrumbs
  
After
breadcrumbs-after

This PR adds | character to languages to differentiate them
  
Before
bfore

After
before

Test Platforms:
- Mobile, Tablet and desktop devices using chrome devices
- Chrome and Firefox browsers
  
* **Please check if the PR fulfills these requirements**

- [x] PR is descriptively titled and links the original issue above
- [x] Before/after screenshots (if this is a layout change)
- [x] Details of which platforms the change was tested on (if this is a browser-specific change)
- [ ] Context for what motivated the change (if this is a change to some content)

### CODE REVIEW

**Comment by pitag-ha** [comment]
Thanks for the PR! :) 

I didn't know @IkehAkinyemi was also changing the layout of the language selector. I thought they would only change its position and fix the overflow that was provoked by the change of position. So now, there is another [PR](https://github.com/ocaml/ocaml.org/pull/1466) also changing the layout of the language selector. I'm really sorry for that! I'm not saying any of them is better, I'm just pointing out that there's a conflict now.

**Comment by 0xull** [comment]
I'm sorry about the conflict in UI layout. I will make out more time making sure to read up on other issues raised to know the most recent update on the project. Just resume back from tooth surgery.

**Comment by dinakajoy** [comment]
I made different commits for each changes. One for the breadcrumbs and one for the languages. You can simply discard the language commit and integrate the breadcrumb commit @pitag-ha 
Or should I revert the commit myself?

**Comment by gs0510** [comment]
I think it's okay for now @dinakajoy, depending on whose PR gets merged first you might have to rebase. :)

**Comment by pitag-ha** [comment]
> I think it's okay for now @dinakajoy, depending on whose PR gets merged first you might have to rebase. :)

The problem with that is that it's not only a conflict in code, but also in content :) @IkehAkinyemi's moves the language selector to the top right and fixes its size to avoid overflow on pages with lots of languages. If we merged that PR and afterwards merged this PR (just resolving the code conflict), we would get the overflow that @IkehAkinyemi is avoiding.

**Comment by dinakajoy** [comment]
I think it's best to leave the language at it's current position (ie beneath the navbar) rather than close to the search bar. As the navbar looks great currently without the language. On mobile, the hamburger is in the middle which is not right.
Instead, I suggest we add the dropdown (and instead of using ... you can use select html tag so it shows the drop down arrow) to the language at it's current location. 
I will revert my commit and only leave that of the breadcrumbs so this pull request can be merged for the breadcrumb.
@pitag-ha and @IkehAkinyemi  please what do you think?

**Comment by dinakajoy** [comment]
I just made a new PR. I renamed the branch for clarification thinking it will simply update the remote branch name but instead it directed me to create a new PR - #1508
This can be closed now. Thank you.

**Comment by pitag-ha** [comment]
> On mobile, the hamburger is in the middle which is not right.

If I understand you correctly, I think that's not exactly right. The language selector would always be in the top right corner. So on mobile, it would be on the right to the hamburger menu. See [here](https://github.com/ocaml/ocaml.org/pull/1466#issuecomment-817240701). Does that sound better?

> can be merged for the breadcrumb

I don't fully understand the idea to move the breadcrumbs, so I'll leave that to other mentors :)

> and instead of using ... you can use select html tag so it shows the drop down arrow

Yes, I also think that the `...` design is improvable. Thanks for the select html tag idea, that might be a good solution! @IkehAkinyemi , have you tried how that would look like?

**Comment by dinakajoy** [comment]
@pitag-ha here is what I am trying to explain - 
The proposed changes
Capture

What other platform looks like - 
Capture2
Capture3

I am just suggesting the language be side by side with the breadcrumb as it is now but with dropdown.
But if you prefer it on the the navbar, it's okay too.

Please check #1378 for the initial issue details raised for the breadcrumb.

**Comment by pitag-ha** [comment]
@dinakajoy , thanks for your input! It's great to discuss different ideas! :)

I've just moved this discussion to the [PR](https://github.com/ocaml/ocaml.org/pull/1466) which it's about.

**Comment by avsm** [comment]
This change looks fine, so I'll go ahead and merge this first so that the discussion about the dropdown bar can be figured out. Thanks @dinakajoy and @IkehAkinyemi for the collaborative discussion (and also hope you are feeling better from the tooth surgery @IkehAkinyemi!)

**Pull request merged**
