### PR TITLE
Scheme-relativize a couple links in prep for https

### PR DESCRIPTION
**Pull request by dsheets**

### CODE REVIEW

**Comment by agarwal** [comment]
@dsheets Since you now have direct commit access, I'm assuming you want to handle your own pull requests. Please say something if you want your pull request reviewed by another person.

**Comment by dsheets** [comment]
Ok. I will ping people when I want review. I assume I should still make pull requests so that watchers are kept up-to-date?

**Comment by pw374** [comment]
In most situations when one doesn't need review and has direct commit access, they don't make pull requests so that the logs are kept a little cleaner.

**Comment by dsheets** [comment]
I disagree. I've seen a number of projects that always do pull requests for notification purposes (even the maintainer in their fork against their master). Whether to actually click "merge this" or to fast-forward via the command line is another matter. I'll defer to whatever you guys want on both of these issues.

**Comment by agarwal** [comment]
@dsheets I agree it is a good practice to always do pull requests, but we haven't followed this so far in this project. I think the main reason is that it would take extra work from people who are mostly volunteering. There hasn't been a problem so far, so there's little motivation to add the extra work.

That said, feel free to do pull requests every time. I have done that for commits I thought should be seen by others.

**Comment by pw374** [comment]
Do you mean pull requests with command-line merge or github-interface merge?

I wouldn't mind the former at all. About the latter, well, for minor changes, I think they'd just pollute the git log, and for larger changes I wouldn't mind much.

**Comment by Chris00** [comment]
On Thu, 14 Aug 2014 12:43:52 -0700, David Sheets wrote:

> I disagree. I've seen a number of projects that always do pull requ 
> ests for notification purposes (even the maintainer in their fork a 
> gainst their master).  Whether to actually click "merge this" or to 
>  fast-forward via the command line is another matter. I'll defer to 
>  whatever you guys want on both of these issues.

Since we start to be more people contributing to the web site — a goo 
d thing! — I think it would be good to do PR so everybody is kept inf 
ormed, at least for "big" changes (minor fixes can be pushed directly 
).

I personally would prefer the merge to be done on the command line to 
 avoid these "merge commits" that Github creates and that are pointle 
ss to me.  When the merged branch is pushed, the PR is automatically  
closed so that does not require extra work (especially if one owns th 
e branch).

What do you all think?

**Comment by Chris00** [comment]
On Thu, 14 Aug 2014 13:39:47 -0700, Philippe Wang wrote:

> Do you mean pull requests with command-line merge or github-interfa 
> ce merge?
> 
> I wouldn't mind the former at all. About the latter, well, for mino 
> r changes, I think they'd just pollute the git log, and for larger  
> changes I wouldn't mind much.

I meant the former.  As Ashish said we have not followed that "rule"  
in the past so I certainly do not want to make it a requirement but i 
t is maybe a practice we should aim for — at least to try it, as a pr 
eparation for further growth.

**Comment by agarwal** [comment]
I'm happy to do pull requests every time, except maybe for completely trivial changes (I sometimes fix a single spelling error).

**Comment by pw374** [comment]
On 14 Aug 2014, at 21:55 pm, Christophe Troestler notifications@github.com wrote:

> On Thu, 14 Aug 2014 12:43:52 -0700, David Sheets wrote:
> 
> > I disagree. I've seen a number of projects that always do pull requ 
> > ests for notification purposes (even the maintainer in their fork a 
> > gainst their master). Whether to actually click "merge this" or to 
> > fast-forward via the command line is another matter. I'll defer to 
> > whatever you guys want on both of these issues.
> 
> Since we start to be more people contributing to the web site — a goo 
> d thing! — I think it would be good to do PR so everybody is kept inf 
> ormed, at least for "big" changes (minor fixes can be pushed directly 
> ).
> 
> I personally would prefer the merge to be done on the command line to 
> avoid these "merge commits" that Github creates and that are pointle 
> ss to me. When the merged branch is pushed, the PR is automatically 
> closed so that does not require extra work (especially if one owns th 
> e branch).
> 
> What do you all think?

Two things:
1. I don’t mind having to make a PR for any nontrivial change. (I can't think that making a PR is worth the trouble when it’s about fixing a few typos.)
2. I believe we should really avoid having in the log something like “[merge by X][commit by X]”.
   I don’t mind having “[merge by X][commit by Y]” as it shows who took the responsibility to merge the PR made by Y, so that it’s easier to ask for motivations if any issue were to arise.

**Comment by Chris00** [comment]
On Thu, 14 Aug 2014 14:32:07 -0700, Philippe Wang wrote:

> I can't think that making a PR is worth the trouble when it’s about 
>  fixing a few typos.)

I agree.  That is what I suggested in my first reply.

> 1. I believe we should really avoid having in the log something lik 
>    e “[merge by X][commit by X]”.  I don’t mind having “[merge by X][c 
>    ommit by Y]” as it shows who took the responsibility to merge the P 
>    R made by Y, so that it’s easier to ask for motivations if any issu 
>    e were to arise.

Not sure I follow you.  Do you or don't you want “[merge by X][commit 
 by X]” in the commit history?

**Comment by agarwal** [comment]
>  Do you or don't you want “[merge by X][commit by X]” in the commit history?

I think he meant if you are merging your own commit, then please use the command line so GitHub won't create the extra item. However, if you are merging someone else's commit, then it's okay (and maybe better) to use the GitHub button because it's good to know who reviewed and merged.

**Comment by dsheets** [comment]
Sounds good to me. Thanks for the discussion, everyone.

**Pull request merged**
