### PR TITLE
Remove OCaml 2017 announcement

### PR DESCRIPTION
**Pull request by pmetzger**
OCaml 2017 was a long time ago, so this probably doesn't belong on the front page any longer.

### CODE REVIEW

**Comment by Chris00** [comment]
I would prefer to have it commented out — rather than removed — as one will need to put it back when the next meeting will be announced.

**Comment by pmetzger** [comment]
@Chris00 As you have requested, I've changed this to comment out the announcement.

**Comment by Chris00** [comment]
Thanks.

**Comment by pmetzger** [comment]
BTW, longer term, I'd suggest that it might be good if there was a distinction between "real" news (new versions of OCaml, OCaml meeting announcements, etc.) and the OCaml planet stuff, but that's not a good discussion for here.

**Pull request merged**
